### ISSUE TITLE
Try to reconnect when mongo connection fails

### ISSUE THREAD

**Issue by daanbeverdam** [vivekratnavel/omniboard#10]
When the app is started while mongo is not yet ready, it crashes. It would be nice to have it try to reconnect. This is especially handy when using docker-compose, because most of the times my omniboard container is up before mongo has fully started up (even with container dependencies set up).

**Comment by vivekratnavel** [comment]
Agreed. I would be happy to accept PR for this.

**Comment by vivekratnavel** [comment]
@daanbeverdam Thanks for creating this issue. Fixed in master. Will be released with v0.0.3.
