### ISSUE TITLE
Feature request: Show experiment count

### ISSUE THREAD

**Issue by flukeskywalker** [vivekratnavel/omniboard#100]
It would be very useful to see a count of the experiments currently being displayed i.e. after applying all filters. 

Using this feature, one could quickly check how many of the experiments on a cluster failed, or how many experiments were run with the certain config values. Ideally the count should be somewhere near the top of the page.

**Comment by vivekratnavel** [comment]
@flukeskywalker I am already working on this along with another big feature. This will be fixed in the next release.

**Comment by flukeskywalker** [comment]
Wonderful. And while I'm here, thanks for your work on Omniboard!
