### ISSUE TITLE
Filter by duration

### ISSUE THREAD

**Issue by eukaryote31** [vivekratnavel/omniboard#102]
Duration is not in the filters drop-down.

**Comment by vivekratnavel** [comment]
This was because, `duration` was a client side column and did not come from the server and could not be supported. I will try to support this feature in the next major release that I am working on, where all the filtering, sorting and computations will be moved to backend. #107

**Comment by vivekratnavel** [comment]
This feature will be supported in v2.0 #107

**Comment by vivekratnavel** [comment]
Omniboard v2.0.0-beta is out. You can try it out with either npm or docker - https://www.npmjs.com/package/omniboard/v/2.0.0-beta.2 
Docker image - vivekratnavel/omniboard:beta
Source code is in branch 'beta' - https://github.com/vivekratnavel/omniboard/tree/beta

Please try it out and give feedback.

**Comment by vivekratnavel** [comment]
Fixed in v2.0.0 - https://github.com/vivekratnavel/omniboard/releases/tag/2.0.0
