### ISSUE TITLE
Variable row width.

### ISSUE THREAD

**Issue by BTickell** [vivekratnavel/omniboard#103]
It seems the notes feature doesn't allow for very long / detailed experiment notes. Is there a way to make more of the notes field visible in one view / make scrolling through a note easier?

**Comment by daniel-sch** [comment]
Additionally on Firefox 67.0 on Windows 10 the text field is so large that the buttons are not visible without resizing the text field.

See this screenshot:
![grafik](https://user-images.githubusercontent.com/360180/58261557-d08d9d00-7d78-11e9-83a6-b1e52e9c80ea.png)
