### ISSUE TITLE
'Error: no response received from server'

### ISSUE THREAD

**Issue by berger-stx** [vivekratnavel/omniboard#108]
I apologize in advance that I am not able to provide detailed debug info at this time...  will try to provide it later

Here are my observations: 

(on chrome and the latest image from dockerhub)

I've been using omniboard without hitch for some time. Today, it started failing with `Error: no response received from server' when you try to load details about an experiment, out of nowhere. No changes were made to the server, just started failing in the middle of a session.  

No errors in logs, but many 304 responses.  Incognito works fine. Maybe a cache issue?

Here's the part that gets me though, same exact problem after clearing chrome's cache and restarting the container. There's no state left after that, so what gives? 

Incognito continues to work fine.

**Comment by khaledvic** [comment]
I had the same problem. after some debugging, it turned out that the ad-blocking plugin is blocking the requests,try disabling it if you have one.

**Comment by berger-stx** [comment]
Ah! Brilliant! That did the trick.
