### ISSUE TITLE
[Bug] - No response was received from the server

### ISSUE THREAD

**Issue by alpapado** [vivekratnavel/omniboard#109]
This started happening recently and only when using **Firefox**.

While the list of experiments loads and shows correctly, I get an `Error: No response was received from the server` when trying to view a specific experiment from the list.  

In addition, from the browser console I see that the GET request to read the specific experiment from MongoDB returns correctly with all the needed information but it is not rendered in the relevant fields.

**Comment by khaledvic** [comment]
maybe something similar to #108 , try to disable the ad-blocker.

**Comment by alpapado** [comment]
That was indeed the issue. Disabling uBlock did the trick. 
Thank you
