### ISSUE TITLE
Add new column from host_info #add_column

### ISSUE THREAD

**Issue by MyadaRoshdi** [vivekratnavel/omniboard#112]
In my example, since we are multiple users and experiments are logged to the same mongodb, I added some extra values to host_info which shows up in the mongodb entry but I'd prefer to be able to add it as a column in omniboard. Is there a way to do that?

**Comment by vivekratnavel** [comment]
@MyadaRoshdi You can now add a custom column with any parameter. For example, to add hostname as a new column, you would add a custom column with path as `host.hostname`.
