### ISSUE TITLE
Close details when deleting

### ISSUE THREAD

**Issue by pizzooid** [vivekratnavel/omniboard#117]
When an experiment is deleted while the details are shown, the details from the deleted experiment keep being displayed. This is especially problematic because they are now shown under the header of a different experiment.

**Comment by vivekratnavel** [comment]
This will be fixed as part of v2.0 #107

**Comment by vivekratnavel** [comment]
Omniboard v2.0.0-beta is out. You can try it out with either npm or docker - https://www.npmjs.com/package/omniboard/v/2.0.0-beta.2 
Docker image - vivekratnavel/omniboard:beta
Source code is in branch 'beta' - https://github.com/vivekratnavel/omniboard/tree/beta

Please try it out and give feedback.

**Comment by vivekratnavel** [comment]
Fixed in v2.0.0 - https://github.com/vivekratnavel/omniboard/releases/tag/2.0.0
