### ISSUE TITLE
Binary artifacts are not served properly

### ISSUE THREAD

**Issue by dzkb** [vivekratnavel/omniboard#12]
Hi,

I'm having issues with binary artifacts, e.g. PNG plots or pickled data. After adding artifacts with sacred by `ex.add_artifact`, Omniboard provides an option to download those artifacts. Currently this works fine only with text data, downloading binary data results in corrupted files. 

I've tried to manually export binary artifact from MongoDB and it works fine – resulting file can be opened without problems. I've tested both PNG files (plots) and pickled DataFrames.

**Steps to reproduce**:
1. Prepare an experiment which saves binary artifacts
2. Execute the experiment
3. Download the artifacts from Omniboard
4. Open downloaded artifacts

**Comment by dzkb** [comment]
@vivekratnavel I meant any binary data. For example pickle files. I cannot unpickle models I downloaded from Omniboard.

**Comment by dzkb** [comment]
You can try this [sample code](https://gist.github.com/dzkb/12e47299168f0ac8375d0b28b931c1e9). After running this experiment, download artifacts using omniboard. Text file will be fine, but the plot will appear corrupted.

**Comment by vivekratnavel** [comment]
@dzkb Thanks for the PR! But, I am working on fixing this bug by implementing a new API in server to serve binary files for download. This will also fix image previews before downloading artifacts.

**Comment by dzkb** [comment]
@vivekratnavel Great! I'm looking forward to it! I'll close my PR then.

**Comment by vivekratnavel** [comment]
Fixed in https://github.com/vivekratnavel/omniboard/releases/tag/0.0.4
