### ISSUE TITLE
Add viewer for image file artifacts?

### ISSUE THREAD

**Issue by nbren12** [vivekratnavel/omniboard#14]
I really appreciate the work you have done on ominiboard, and really like the notes feature.

I frequently save matplotlib plots to track the progress of my models as they are trained, and I am wondering if it would be possible to add a image viewer for these artifacts.

Thanks!

**Comment by vivekratnavel** [comment]
Sure. I added image viewer in the latest release - https://github.com/vivekratnavel/omniboard/releases/tag/0.0.4

Which version of omniboard are you using? And what is the image format of your matplotlib plots?

**Comment by nbren12** [comment]
Wonderful! Thank you. I just updated to the latest version, and it works.

**Comment by vivekratnavel** [comment]
Great!
