### ISSUE TITLE
Getting Error: Command Not Supported, when trying to connect to Azure Cloud Cosmos Mongo DB instance via docker

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [vivekratnavel/omniboard#144]
Hi, I try to connect to Azure cloud cosmos (mongo DB) instance, which stores the results of the experiments, by using docker-compose with omniboard.

When doing so, I obtain the following exception in the omniboard (see attached picture):
![image](https://user-images.githubusercontent.com/4510224/64239727-08bc8400-cf01-11e9-9c2b-60dbbce075e0.png)

The mondo DB connection string, provided in docker, is basically the connection string, which is provided by Azur Cosmos DB , with one addition of db after the last slash (before parameters ?)

The stdout from docker-compose run includes string, that the connection to mongodb://<CONNECTION_DETAILS> was established successfully

and then following details:

```
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:03 +0000] "GET / HTTP/1.1" 304 - 6.946 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:03 +0000] "GET /static/css/main.e64d45ec.css HTTP/1.1" 304 - 1.066 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:03 +0000] "GET /static/js/main.be790c11.js HTTP/1.1" 304 - 1.059 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:04 +0000] "GET /static/media/glyphicons-halflings-regular.448c34a5.woff2 HTTP/1.1" 304 - 0.411 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:04 +0000] "GET /api/v1/database HTTP/1.1" 304 - 3.527 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:04 +0000] "GET /favicon.ico?v=1 HTTP/1.1" 200 7171 2.795 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:04 +0000] "GET /api/v1/Omniboard.Settings HTTP/1.1" 304 - 36.108 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:04 +0000] "GET /api/v1/Omniboard.Columns HTTP/1.1" 304 - 345.784 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:04 +0000] "GET /api/v1/Runs?select=_id,heartbeat,experiment,command,host,stop_time,config,result,start_time,resources,format,status,omniboard,metrics,meta&sort=-_id&query=%7B%7D HTTP/1.1" 304 - 36.086 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:04 +0000] "GET /api/v1/Runs?distinct=omniboard.tags HTTP/1.1" 400 475 37.530 ms
omniboard_cloud_1  | ::ffff:172.19.0.1 - - [04/Sep/2019:08:41:04 +0000] "GET /api/v1/Omniboard.Config.Columns HTTP/1.1" 304 - 179.289 ms
```

**Comment by serhiy-yevtushenko** [comment]
Further clarification: Azure Cosmos DB supports only version 3.2 of Mongo DB Wire protocol (see https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/cosmos-db/mongodb-introduction.md)

I have tried as well running version 1.8.1 against Azure Cosmos DB mongo instance and still getting this error.

Could you please clarify, which version of OmniBoard is compatible with MongoDB Version 3.2?

**Comment by vivekratnavel** [comment]
@serhiy-yevtushenko Omniboard uses distinct queries and you will need to enable aggregation pipeline in Azure Cosmos - https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-feature-support#aggregation-pipeline

This issue is a duplicate of https://github.com/vivekratnavel/omniboard/issues/41

And v1.8.1 is the latest version that can be used with Mongo 3.2.

**Comment by serhiy-yevtushenko** [comment]
Thanks you for the answer and clarification. 

Just a short notice - I got this issues as well with the v1.8.1 and 1.8.0. I was able to solve it by enabling aggregation pipeline in Cosmos DB and now it functions with version 2.1.0
