### ISSUE TITLE
Upon connecting to CosmosDB Mongo DB, omniboard code throws exception "Unrecognized parameter to $lookup: let"

### ISSUE THREAD

**Issue by serhiy-yevtushenko** [vivekratnavel/omniboard#145]
I'm getting the following exception upon connectng to Cosmos Mongo DB database:

Omniboard version is 2.1.0, which is being run from docker.

omniboard_cloud_1  | ::ffff:172.19.0.1 - - [06/Sep/2019:13:21:31 +0000] "GET /api/v1/Runs?select=_id,heartbeat,experiment,command,host,stop_time,config,duration,result,start_time,resources,format,status,omniboard,metrics,meta,F_beta_0.5&sort_by=_id&order_by=-1&query=%7B%22$and%22:[%7B%22$or%22:[%7B%22status%22:%7B%22$eq%22:%22RUNNING%22%7D%7D]%7D]%7D&limit=50 HTTP/1.1" 500 148 63.160 ms
omniboard_cloud_1  | MongoError: Unrecognized parameter to $lookup: let
omniboard_cloud_1  |     at Connection.<anonymous> (/usr/omniboard/node_modules/mongodb-core/lib/connection/pool.js:443:61)
omniboard_cloud_1  |     at Connection.emit (events.js:198:13)
omniboard_cloud_1  |     at processMessage (/usr/omniboard/node_modules/mongodb-core/lib/connection/connection.js:364:10)
omniboard_cloud_1  |     at TLSSocket.<anonymous> (/usr/omniboard/node_modules/mongodb-core/lib/connection/connection.js:533:15)
omniboard_cloud_1  |     at TLSSocket.emit (events.js:198:13)
omniboard_cloud_1  |     at addChunk (_stream_readable.js:288:12)
omniboard_cloud_1  |     at readableAddChunk (_stream_readable.js:269:11)
omniboard_cloud_1  |     at TLSSocket.Readable.push (_stream_readable.js:224:10)
omniboard_cloud_1  |     at TLSWrap.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
omniboard_cloud_1  | Query took 0.077 seconds.

The Azure Cosmos Database has additionally enabled features Aggregation Pipeline 
and MongoDB 3.4 wire protocol (version 5)

**Comment by vivekratnavel** [comment]
@serhiy-yevtushenko You are trying to connect to MongoDB < 4.0 with Omniboard v2.x which will not work. Try using Omniboard v1.8.1 and it should work.

**Comment by serhiy-yevtushenko** [comment]
The strange thing that this exception is not happening on every run, but only sometimes. That's why I tried using version 2.1.0 (My observation was, that version 1.8.1. would not work on Cosmos DB as well, if aggregation was not enabled, and I was getting on my machine version 2.1.0 mostly working (and getting this exception in rare cases).

**Comment by vivekratnavel** [comment]
@serhiy-yevtushenko You will need to enable aggregation pipeline in Azure CosmosDB for any version of Omniboard to work as expected. And if you want to try Omniboard v2.x, you must connect to Mongo DB >= 4.0 for it to work as expected. It is a breaking change because some of the queries used by Omniboard v2.x are not supported in MongoDB < 4.x. So, if you use Omniboard v2.x with MongoDB 3.x, you will see such exceptions and inconsistencies.
