### ISSUE TITLE
with beat_interval, metric plot and captured output are empty

### ISSUE THREAD

**Issue by dvorak0** [vivekratnavel/omniboard#147]
`python main.py -m sacred --beat_interval=100` runs my experiments. But I see nothing from the metric plot and captured output.

**Comment by vivekratnavel** [comment]
@dvorak0 Can you verify if metrics and captured out are available in the mongodb?

**Comment by dvorak0** [comment]
@vivekratnavel I checked and found that it's empty in db. Could it be a problem related to sacred?

**Comment by vivekratnavel** [comment]
Yes, please create an issue in sacred. I am closing this issue since it cannot be fixed in omniboard.
