### ISSUE TITLE
All fields for a running experiment are displayed as "pending" when a column doesn't fit

### ISSUE THREAD

**Issue by dvorak0** [vivekratnavel/omniboard#150]
I like the column feature and usually use a "best_result, min of testing.loss" metric.

But I found All fields for a running experiment are displayed as "pending" when a column doesn't fit.

For example, I have both trainning.loss and testing.loss for "Metrics Plot" for ID=1 experiment. Then the column "best_result, min of testing.loss" works well. But when I have another experiment ID=2 which only has trainning.loss for "Metrics Plot". The display in omniboard is strange. All columns for ID=2 are displayed as "pending", making me confused.

Should this be considered to be improved? I think a "null value" or "inf value" only for the column "best_result, min of testing.loss" and other columns remain as it should be is better.

**Comment by vivekratnavel** [comment]
It is indeed strange. Can you post the response of API request `/api/v1/Runs` from the network tab in dev tools?

You should see "Pending" only when Omniboard is loading data from the server. Also, can you post a screen-shot of this ?

**Comment by dvorak0** [comment]
![Capture](https://user-images.githubusercontent.com/2220369/65153270-0e1ae200-da5c-11e9-8615-430579b6d59e.PNG)
@vivekratnavel  Here you are.

Thanks for you help.
