### ISSUE TITLE
add tags from code

### ISSUE THREAD

**Issue by erap129** [vivekratnavel/omniboard#151]
Hello,  
I really like the 'tags' feature and it would really help me if it was possible to somehow inject tags from the python code via the MongoObserver.  
Is this possible in some way?  
Thanks a lot

**Comment by vivekratnavel** [comment]
You can use config.tags to set tags from python. Let me know if it works for you.

**Comment by erap129** [comment]
Thanks for the comment but I think it doesn't work.  
I tried this:
`@ex.main`
`def main(_config):`
    `_config.tags = ['test_tag']`
  
and I also tried adding a "Tags" or "tags" dictionary to the normal configuration and none of the ways seem to add tags to Omniboard.

**Comment by vivekratnavel** [comment]
@erap129 I have fixed all the bugs related to this issue and added support for this feature in the latest release of Omniboard. I have also updated the documentation. Please update Omniboard and let me know if it works.
