### ISSUE TITLE
Omniboard 2.2.0 does not display run comments

### ISSUE THREAD

**Issue by alpapado** [vivekratnavel/omniboard#152]
Upon upgrade to version 2.2 (from a version below v2), omniboard no longer displays sacred comments added via the -c flag, in the notes column. This is also happening for previous experiments, whose comments were being displayed properly prior to the upgrade.

**Comment by vivekratnavel** [comment]
@alpapado Thanks for filing this issue! Omniboard v2.0 underwent major refactoring in the code and moved all the computations to server side. I will track this as a feature request to combine and display comments in the "Notes" column.

**Comment by alpapado** [comment]
Hi. Any news on that front?

**Comment by vivekratnavel** [comment]
Hi @alpapado,

This piece of code is supposed to display `meta.comment` in Runs collection as `Notes` in the UI.

Can you check your MongoDB collection to see if you have `meta.comment` populated in the Runs collection?

**Comment by alpapado** [comment]
Yes meta.comment is populated in the mongoDB as seen in mongo compass:

![sacred](https://user-images.githubusercontent.com/11426919/73463644-46291e80-4386-11ea-9f2e-f39783bfbccb.png)

Yet, the notes field in omniboard does not show the comment :(

**Comment by vivekratnavel** [comment]
Hi @alpapado,

Omniboard looks for `meta.comment` and I see that your MongoDB has the comment stored in `meta.options.--comment`. Can you post the complete `meta` object?

**Comment by alpapado** [comment]
Sure. There you go. 

![sacred](https://user-images.githubusercontent.com/11426919/73465459-1a5b6800-4389-11ea-872f-d60d1b75c3c9.png)

My bad about before. It seems there is also an external comment field i.e. meta.comment. So the code should work I guess?

**Comment by vivekratnavel** [comment]
Thanks for this! I will dig deeper and debug on this issue.

**Comment by vivekratnavel** [comment]
Hi @alpapado, I have fixed this issue and a new version of Omniboard is on its way. Please update your Omniboard to the latest version and you should see all your existing notes in Omniboard.

Let me know if you have any issues.
