### ISSUE TITLE
Allow to associate a results with uploaded files like images

### ISSUE THREAD

**Issue by dmiyakawa** [vivekratnavel/omniboard#154]
I'd like to attach files related to each experiments, which are indirect results of the experiments.  For example in machine learning, training results may contain some example screenshots of actual detections.

**Comment by alpapado** [comment]
This sounds like a use case for Sacred's artifacts.

**Comment by vivekratnavel** [comment]
@dmiyakawa I agree with @alpapado. You can attach those images as Sacred Artifacts and Omniboard will display those artifacts under each experiment run.
