### ISSUE TITLE
Delete all failure or interrupted rows

### ISSUE THREAD

**Issue by Guptajakala** [vivekratnavel/omniboard#163]
Hi,
This visualizer is pretty cool! 
I'm wondering if there is such feature to delete all failure or interrupted rows, or if you plan to add? Thanks!

**Comment by vivekratnavel** [comment]
Hi @Guptajakala,

I am planning to add multi-delete feature via #115 

You can then add a filter for failed or interrupted rows, select all rows and then delete them all at once.
