### ISSUE TITLE
Add metric column gives Error:undefined

### ISSUE THREAD

**Issue by melodieboillet** [vivekratnavel/omniboard#167]
Hi, 

I'm new to Sacred with Omniboard and I'm facing an issue when trying to add a new column. When I choose to add a metric, I got an "Error: undefined" and all experiment disappear until I remove the added metric column. See the two following images showing this problem.

![add_column](https://user-images.githubusercontent.com/50051238/69163224-21930980-0aee-11ea-8148-7f242c031f99.png)
![after_adding](https://user-images.githubusercontent.com/50051238/69163229-23f56380-0aee-11ea-950b-a7b4549a06f1.png)

By the way, where are the columns coming from ? I thought it was from the config but only a few of them are present.

Thanks

**Comment by Polyphenolx** [comment]
After running into the same issue, I found that the node server would give `MongoError: Unrecognized expression '$toObjectId'`. A quick google search found that `$toObjectId` is a _new_ method to mongodb version 4- executing `mongod --version` gave me 3.6.8. After upgrading to version 4, my issue was resolved.

**Comment by vivekratnavel** [comment]
Omniboard v2.x is only compatible with MongoDB >= 4.0. Please upgrade MondoDB as @Polyphenolx suggested or downgrade Omniboard to v1.x.

**Comment by melodieboillet** [comment]
Thanks for your answers, it works now.
