### ISSUE TITLE
How to bind other port, not only 9000

### ISSUE THREAD

**Issue by cheneyoung** [vivekratnavel/omniboard#172]
like the title, now I want to user other port, how can I  do?

**Comment by jykzel** [comment]
1. export PORT=9001
2. omniboard -m localhost:27017:db_name

**Comment by arisliang** [comment]
seems to be pretty generic env variable, would be nice to be able to specify it via command line args.

**Comment by vivekratnavel** [comment]
@arisliang I am open to accepting a pull request.
