### ISSUE TITLE
Suggestion: Change tag mongodb path from 'runs.omniboard.tags' to 'runs.info.omniboard.tag'

### ISSUE THREAD

**Issue by skyser2003** [vivekratnavel/omniboard#173]
I am using tags to filter different model training runs.
Tags are currently saved in `runs.omniboard.tags` in mongodb, and only can be assigned via omniboard web ui and not in python code.
If save path is changed to `runs.info.omniboard.tags`, than you can assign tag within python like this.

```
ex = Experiment()
ex.run(info={"omniboard":{"tags": ["tag1", "tag2"]}})
```

Backward compatibility can be easily done, you can just read in tags from old path but no more update from that path.

**Comment by vivekratnavel** [comment]
@skyser2003 Thanks for your suggestion! You can add tags to experiments from python code by adding tags to `config.tags` as a comma separated string.

```
@ex.config
def cfg():
  tags = tag1,tag2
```

This feature already exists in omniboard. Please give it a try and let me know if it works for you.

**Comment by skyser2003** [comment]
Oh thanks, I just couldn't find any documentation mentioning this feature.
It works well.

**Comment by vivekratnavel** [comment]
@skyser2003 This feature is documented here - https://vivekratnavel.github.io/omniboard/#/usage?id=add-tags-using-configs
