### ISSUE TITLE
Is there any way to remember the display style

### ISSUE THREAD

**Issue by IIAT-MR-LL** [vivekratnavel/omniboard#176]
In chrome, Is there any way to remember the display style as below, I found it always return to default style after few hours.

- order of the display column list, 
- which column is hide or display, 
- and the filter i create

**Comment by vivekratnavel** [comment]
Currently, all of these settings are stored in browsers local storage. If you use the same browser session, then all the settings should be remembered by Omniboard.

**Comment by IIAT-MR-LL** [comment]
So that is say, if the chrome restart, then the setting will be gone in chrome?

**Comment by vivekratnavel** [comment]
@IIAT-MR-LL Unless you clear local storage, the settings should be remembered by Omniboard.

**Comment by jrfan** [comment]
So...the notes part in the web page where I can enter some notes is also only stored in browsers? I think it would be interesting to store the notes in mongodb and share with other co-workers~

**Comment by vivekratnavel** [comment]
@jrfan The notes and tags are all stored in the database. Only the settings are stored in the browser. A few example settings include 
- Show / hide columns
- Column order
- Column widths
- Filters

**Comment by jrfan** [comment]
Oh I see, sorry, there is some errors in my Firefox browser, where the check mark is missing as shown below, so I didn't know how to save the notes. When I change the browser to Edge, I can see a part of check mark which works!
![图片](https://user-images.githubusercontent.com/33249614/77130470-0da6e680-6a93-11ea-8cc8-ea6836795410.png)

**Comment by vivekratnavel** [comment]
You can resize the Notes input TextArea by dragging it from right bottom to see the checkbox. You can also increase the default height of each row by changing this setting in Omniboard. https://vivekratnavel.github.io/omniboard/#/usage?id=change-timezone

**Comment by jrfan** [comment]
@vivekratnavel Thanks! That's very kind of you ! This really helps~

**Comment by vivekratnavel** [comment]
@jrfan I am glad it helped you!
