### ISSUE TITLE
Error when adding metric column - unrecognized expression $average

### ISSUE THREAD

**Issue by lotsoffood** [vivekratnavel/omniboard#178]
Hello,

I have multiple different experiments (with different metrics for each experiment) being written into a MongoDB (4.0.5) database with Omniboard (2.4.3) running as well. When trying to add a metric column (choose a name, metric, and "average"), I get an error in the web interface: `Error: Undefined`. The trace looks like:

```
MongoError: Unrecognized expression '$average'
    at Connection.<anonymous> (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/connection/pool.js:460:61)
    at Connection.emit (events.js:188:13)
    at processMessage (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:368:10)
    at Socket.<anonymous> (/usr/lib/node_modules/omniboard/node_modules/mongoose/node_modules/mongodb/lib/core/connection/connection.js:537:15)
    at Socket.emit (events.js:188:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)
```

Any thoughts on a potential fix?

**Comment by vivekratnavel** [comment]
If you are running Mongo v4.0.5, can you try to run a query with $avg in Mongo shell?

If you get the same error when you try to run $avg on any of the metrics data in Mongo shell, then nothing much can be done in Omniboard since it would be something specific to your metrics data. If not, I will take a look.

**Comment by lotsoffood** [comment]
Hi @vivekratnavel - thanks for the quick response.

It looks like OmniBoard is using `$average`, and from MongoDB docs it doesn't seem there is an `$average` expression. Instead, they show `$avg`. Is there somewhere in the OmniBoard code that `$average` is being used instead of `$avg`? I haven't been able to log into my console yet to test unfortunately.

**Comment by vivekratnavel** [comment]
I think this might be it -
https://github.com/vivekratnavel/omniboard/blob/191afecf4f0d8a4294f5ef84fac4d5e7570a2c00/web/src/components/MetricColumnModal/metricColumnModal.js#L305

https://github.com/vivekratnavel/omniboard/blob/master/server/runs.response.js#L331

But, can you please confirm by manually updating the row in MongoDB with `avg` instead of `average`? The newly added metric columns should be stored on `omniboard.metric.columns` - https://vivekratnavel.github.io/omniboard/#/quick-start?id=metric-columns

**Comment by lotsoffood** [comment]
Hey @vivekratnavel - the `$avg` operator works fine in the Mongo shell, but `$average` does not. See below:

Works:
```
> db.metrics.aggregate( [ { $group: { _id: "name", avgAmount: { $avg : "$run_id" } } } ] )
{ "_id" : "name", "avgAmount" : 209.12811745776347 }
```

Doesn't work:
```
> db.metrics.aggregate( [ { $group: { _id: "name", avgAmount: { $average : "$run_id" } } } ] )
2020-01-06T19:06:54.863+0000 E QUERY    [js] Error: command failed: {
	"ok" : 0,
	"errmsg" : "unknown group operator '$average'",
	"code" : 15952,
	"codeName" : "Location15952"
} : aggregate failed :
_getErrorWithCode@src/mongo/shell/utils.js:25:13
doassert@src/mongo/shell/assert.js:18:14
_assertCommandWorked@src/mongo/shell/assert.js:534:17
assert.commandWorked@src/mongo/shell/assert.js:618:16
DB.prototype._runAggregate@src/mongo/shell/db.js:260:9
DBCollection.prototype.aggregate@src/mongo/shell/collection.js:1062:12
@(shell):1:1
>
```

This is what a single record actually looks like in `db.metrics`; I couldn't figure out the Mongo syntax for taking the average of an array, but just FYI:

`{ "_id" : ObjectId("sdfsadfdsaf2332"), "name" : "My_Metric", "run_id" : 16, "steps" : [ 201907, 201908, 201909, 201910 ], "timestamps" : [ ISODate("2019-12-18T19:23:21.341Z"), ISODate("2019-12-18T19:23:21.341Z"), ISODate("2019-12-18T19:23:21.341Z"), ISODate("2019-12-18T19:23:21.341Z") ], "values" : [ 0.6347666034155598, 0.5825929899856938, 0.6638843255144382, 0.6822171542996998 ] }`

**Comment by lotsoffood** [comment]
Sorry, I see what you are asking me to do now. Give me just a minute, I am trying to navigate my way around MongoDB.

**Comment by vivekratnavel** [comment]
@lotsoffood If you are having trouble navigating around Mongo, give mongo express a try - https://github.com/mongo-express/mongo-express#readme

**Comment by lotsoffood** [comment]
@vivekratnavel  The manual update from `average` to `avg` fixed it! Thank you.

**Comment by vivekratnavel** [comment]
@lotsoffood Great! Can you post a pull request for the fix? It will only require changing `average` to `avg` here - https://github.com/vivekratnavel/omniboard/blob/191afecf4f0d8a4294f5ef84fac4d5e7570a2c00/web/src/components/MetricColumnModal/metricColumnModal.js#L305
and some basic testing

**Comment by vivekratnavel** [comment]
You can refer to this documentation to start omniboard in local for development - https://vivekratnavel.github.io/omniboard/#/development

**Comment by lotsoffood** [comment]
I can put in a PR real quick with `git` if I have access (without testing), but am having trouble with the `yarn` based instructions above and don't have anymore time to troubleshoot now. I may have to revisit at a later date

**Comment by lotsoffood** [comment]
Made the fix but don't have permissions to push the `hotfix/average` branch to the repo.

**Comment by vivekratnavel** [comment]
@lotsoffood That's fine! Thanks for your effort in finding this bug and trying to fix it. I fixed it and pushed the changes. Average should work fine from the next version of Omniboard.
