### ISSUE TITLE
Export and import experiments

### ISSUE THREAD

**Issue by WangLiwen1994** [vivekratnavel/omniboard#179]
I need to backup some key experiments to avoid accidentally deleting. Is there a method to export one experiment, or move it to another database?

Thank you!

**Comment by vivekratnavel** [comment]
Omniboard is a tool to visualize sacred experiments stored in MongoDB. You can always backup and restore your MongoDB using Mongo Tools such as mongodump - https://docs.mongodb.com/manual/reference/program/mongodump/

I am not planning to add this as a feature in Omniboard.
