### ISSUE TITLE
Deleting experiment deletes source files even when other experiments depend on them

### ISSUE THREAD

**Issue by sjTaylor** [vivekratnavel/omniboard#182]
sacred version: 0.7.5 and 0.8.1
omniboard version: 2.4.5

If an experiment is deleted the source files are also deleted.
This causes issues when two experiments share source file versions (i.e. source files did not change between runs).
Re-running the experiment after deleting (w/o modifying the source) will not make the source view-able in the older experiments.

Steps to reproduce:
1. Run an experiment (exp_1)
2. Re-run the same experiment (exp_2)
3. Delete exp_2 in omniboard
4. exp_1 source no longer view-able or download-able ("Error: No files are available to download")
5. re-run same experiment (exp_3)
6. exp_1 source still not view-able, but source view-able for exp_3

This bug was probably introduced while closing #97 

The code below can be used as an experiment to re-produce the above issue.

```python
from sacred import Experiment
from sacred.utils import apply_backspaces_and_linefeeds

ex = Experiment()
ex.captured_out_filter = apply_backspaces_and_linefeeds


@ex.config
def cfg():
    thingy = ["a"]


@ex.automain
def print_thingy(thingy):
    print(thingy)
    print("len", len(thingy))

```

**Comment by vivekratnavel** [comment]
@sjTaylor Thanks for raising this issue with details to reproduce. I am going to fix this soon. This bug is being tracked at #153
