### ISSUE TITLE
Usage (docker) without --link

### ISSUE THREAD

**Issue by loeiten** [vivekratnavel/omniboard#19]
I tried setting up Omniboard as described in the [docks](https://github.com/vivekratnavel/omniboard#usage-docker) as follows

```sh
docker run --name sacred-db -p 27017:27017 -v /path/to/database/:/data/db -d
docker run -it --rm -p 9000:9000 --name omniboard --link sacred-db:mongo vivekratnavel/omniboard -m mongo:27017:sacre
```

and everything is working as expected.

However, reading from the docker [documentation](https://docs.docker.com/network/links/), I see that `--link` is deprecated

> Warning: The --link flag is a legacy feature of Docker. It may eventually be removed. Unless you absolutely need to continue using it, we recommend that you use user-defined networks to facilitate communication between two containers instead of using --link

What is the preferred way to run through docker without using the `--link` option?

I tried

```sh
docker network create sacred-network
docker run --name sacred-db -p 27017:27017 -v /path/to/database/:/data/db -d --net=sacred-network mongo
docker run -it --rm -p 9000:9000 --name omniboard vivekratnavel/omniboard --net=sacred-network -m mongo:27017:sacred
```

But it I only get a `failed to connect to server` error:

```
> omniboard@0.0.4 prod /usr/omniboard
> cross-env NODE_ENV=production node dist/index.js "--net=sacred-network" "-m" "mongo:27017:sacred"

Omniboard is listening on port 9000!
2018-11-13T11:41:53.551Z 'MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]'
Retrying in 20 seconds...
Retrying first connect...
(node:29) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
2018-11-13T11:42:13.556Z 'MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]'
Retrying in 20 seconds...
Retrying first connect...
2018-11-13T11:42:33.554Z 'MongoNetworkError: failed to connect to server [mongo:27017] on first connect [MongoNetworkError: getaddrinfo ENOTFOUND mongo mongo:27017]'
Failed to establish connection to mongodb://mongo:27017/sacred after 2 retries. Exiting now...
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! omniboard@0.0.4 prod: `cross-env NODE_ENV=production node dist/index.js "--net=sacred-network" "-m" "mongo:27017:sacred"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the omniboard@0.0.4 prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-11-13T11_42_33_587Z-debug.log
```

**Comment by vivekratnavel** [comment]
@loeiten Thanks for trying Omniboard! Is your mongo container also within the same network (sacred-network) ?

**Comment by loeiten** [comment]
@vivekratnavel Well, thank you for creating Omniboard :).

I'm by no means an expert on docker, but if I understand it correctly, they are on the same network.

As far as I understand, this is how the commands above works
 ```
docker network create sacred-network
```
creates the network
```
docker run --name sacred-db -p 27017:27017 -v /path/to/database/:/data/db -d --net=sacred-network mongo
```
creates the `mongo` container, adds it to the `sacred-network` and exposes port `27017`. Finally
```
docker run -it --rm -p 9000:9000 --name omniboard vivekratnavel/omniboard --net=sacred-network -m mongo:27017:sacred
```
creates the `omniboard` container, adds it to the `sacred-network` and exposes port `9000`

**Comment by vivekratnavel** [comment]
@loeiten Sorry! I missed your mongo container creation part in the first comment. 

Could you please try this?
`docker run -it --rm -p 9000:9000 --name omniboard --net=sacred-network vivekratnavel/omniboard -m sacred-db:27017:sacred`

Here hostname should be the name of your mongo container. In the docs, it is `mongo` because of alias used in `link`. Please let me know if the above command doesn't work.

**Comment by loeiten** [comment]
That did the trick :D.
Thanks 👍 

Will it be beneficial to change the docs then? To use the `--net` rather than `--link`?

**Comment by vivekratnavel** [comment]
Updated the docs with `--net`. Thanks!
