### ISSUE TITLE
Feature Suggestion: add scatter mark for each tick in metric's graphs

### ISSUE THREAD

**Issue by alberto-oliveira** [vivekratnavel/omniboard#195]
A small issue with the way graphs for metrics are presented. There are two issues with the current way graphs are shown: (1) It is difficult to know which are the steps of the graph, since the ticklabels in the x-axis are not always conformant to the graphs. (2) when you have a single global metric, recorded for one step only, it doesn't show at the graph (only if you hover the mouse). It would help visualization if scatter marks were added to each step in the graph, with the option of turning it off in case the graph has a very big x-axis.

**Comment by vivekratnavel** [comment]
@alberto-oliveira You can now choose between different plot modes :)

<img width="1110" alt="Screen Shot 2020-05-29 at 1 26 53 AM" src="https://user-images.githubusercontent.com/1051198/83238986-0ca5cb80-a14c-11ea-8a6d-4eacfe3de9eb.png">

Please try out the latest version of Omniboard and let me know if it works for you. Thanks!
