### ISSUE TITLE
Delete button not available until two rows are selected

### ISSUE THREAD

**Issue by gkanwar** [vivekratnavel/omniboard#201]
This appears to be a bug, although maybe this is a feature for a reason I don't understand. We can't delete rows until >= 2 have been selected.

If indeed a bug, it's a quick fix at line: https://github.com/vivekratnavel/omniboard/blob/586c43c8a871265104e4e9bd2823f43d4d01c371/web/src/components/RunsTable/runsTable.js#L1000

**Comment by vivekratnavel** [comment]
To delete a single run, you can hover over the id column and click on delete icon.
https://vivekratnavel.github.io/omniboard/#/usage?id=delete-an-experiment-run

The delete button on the top is for multi-delete.

**Comment by gkanwar** [comment]
Definitely true, but I don't see a reason why a single selection shouldn't be deletable using this button? As a user it's confusing to select a run and not see the delete button enabled.

**Comment by vivekratnavel** [comment]
Sure, I would be happy to accept a PR for this. Thanks!
