### ISSUE TITLE
Some filters seem broken after release 2.8.0

### ISSUE THREAD

**Issue by alvarovalcarce** [vivekratnavel/omniboard#205]
An error message indicating "Invalid project" and "specification contains two conflicting paths" is displayed when I enable a parameter filter for a nested configuration.

**Comment by gkanwar** [comment]
Could you open up a developer console in the browser and check which api calls are causing the issue? By nested configurations you mean sacred configs inside scopes?

**Comment by alvarovalcarce** [comment]
Hi,
Yes, I mean Sacred configs inside scopes.

The error message is:

Error: Invalid $project :: caused by :: specification contains two conflicting paths. Cannot specify both 'config.learn.ue_internal_state_size' and 'config.learn': { _id: 1, experiment.name: 1, start_time: 1, status: 1, omniboard.tags: 1, duration: 1, result: 1, Rval SEM: 1, IC: 1, Rval Avg Inst: 1, L_a avg: 1, Rtr Avg Rep0: 1, Qmax Mean Last: 1, Qmax Inst Mean: 1, Qmax Inst Last: 1, Rval Max: 1, config.env: 1, config.learn: 1, config.sacred: 1, config.seed: 1, config.experiment.n_repetitions: 1, config.experiment.n_train_episodes: 1, stop_time: 1, config.tags: 1, config.learn.ue_internal_state_size: 1, info.metrics: 1, heartbeat: 1 }

The General request header is:

Request URL: http://127.0.0.1:11000/sacred0006/api/v1/Runs?select=_id,experiment.name,start_time,status,omniboard.tags,duration,result,Rval+SEM,IC,Rval+Avg+Inst,L_a+avg,Rtr+Avg+Rep0,Qmax+Mean+Last,Qmax+Inst+Mean,Qmax+Inst+Last,Rval+Max,config.env,config.learn,config.sacred,config.seed,config.experiment.n_repetitions,config.experiment.n_train_episodes,stop_time,config.tags&sort_by=_id&order_by=-1&query=%7B%22$and%22:[%7B%22_id%22:%7B%22$gte%22:893%7D%7D,%7B%22config.learn.ue_internal_state_size%22:%7B%22$eq%22:2%7D%7D]%7D&limit=50
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade

**Comment by gkanwar** [comment]
Thanks! This doesn't seem related to the recent change bb8adae9, so I'm a bit confused why this would show up as of 2.8.0. What older version were you at?

**Comment by alvarovalcarce** [comment]
I was using 2.7.4 without problem.

**Comment by gkanwar** [comment]
Okay. To make sure I understand: in the above are your custom config scopes called "learn" and "experiment"?

**Comment by gkanwar** [comment]
@vivekratnavel The issue appears to be with scoped columns not have '.' replaced with something else. I don't know how sacred handles this by default. Database code shouldn't have changed in 2.8.0 so confused as to why this appears now, but maybe you have more insight?

**Comment by vivekratnavel** [comment]
@alvarovalcarce Can you confirm if the same filter on nested config 'config.learn.ue_internal_state_size' works in 2.7.4?

**Comment by alvarovalcarce** [comment]
@gkanwar , Yes "learn" and "experiment" are two of my config scopes.
@vivekratnavel ,Yes, I confirm that the same filter works in 2.7.4.

I add next the HTTP network traces for both versions. These are captured from the moment I click the button "Add filter". Auto refresh is disabled in both cases.

**Network traces in the 2.7.4 version:**
Request URL: http://127.0.0.1:11000/api/v1/Omniboard.Metric.Columns
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 1209
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:49:16 GMT
ETag: W/"4b9-giPN6cc+volFVxHFtW2zFg8X2CU"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
If-None-Match: W/"4b9-giPN6cc+volFVxHFtW2zFg8X2CU"
Referer: http://127.0.0.1:11000/?selectedRows=%5B%5D
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36


Request URL: http://127.0.0.1:11000/api/v1/Omniboard.Custom.Columns
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 1190
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:49:16 GMT
ETag: W/"4a6-4EfZzq5ishTVV40md3fl/U/nTkc"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
If-None-Match: W/"4a6-4EfZzq5ishTVV40md3fl/U/nTkc"
Referer: http://127.0.0.1:11000/?selectedRows=%5B%5D
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

Request URL: http://127.0.0.1:11000/api/v1/Runs?select=experiment.name,start_time,status,omniboard.tags,duration,result,_id,config.env.bler,config.env.initial_empty_buffer,config.env.n_ues,config.env.n_tx_sdus,config.env.t_max,config.learn.epsilon,config.learn.epsilon_decay_rate,config.learn.epsilon_min,config.learn.learning_rate,config.learn.ue_internal_state_size,config.experiment.n_repetitions,config.experiment.n_train_episodes,Rval+SEM,IC,Rval+Avg+Inst,Rtr+Avg+Rep0,Qmax+Mean+Last,Qmax+Inst+Mean,Qmax+Inst+Last,Rval+Max,config.tags&sort_by=_id&order_by=-1&query=%7B%22$and%22:[%7B%22config.learn.ue_internal_state_size%22:%7B%22$eq%22:2%7D%7D]%7D&limit=50
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 39705
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:49:16 GMT
ETag: W/"9b19-udhNWabUUxdqA87kJEvGcjanV/k"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
If-None-Match: W/"9b19-udhNWabUUxdqA87kJEvGcjanV/k"
Referer: http://127.0.0.1:11000/?selectedRows=%5B%5D
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
select: experiment.name,start_time,status,omniboard.tags,duration,result,_id,config.env.bler,config.env.initial_empty_buffer,config.env.n_ues,config.env.n_tx_sdus,config.env.t_max,config.learn.epsilon,config.learn.epsilon_decay_rate,config.learn.epsilon_min,config.learn.learning_rate,config.learn.ue_internal_state_size,config.experiment.n_repetitions,config.experiment.n_train_episodes,Rval SEM,IC,Rval Avg Inst,Rtr Avg Rep0,Qmax Mean Last,Qmax Inst Mean,Qmax Inst Last,Rval Max,config.tags
sort_by: _id
order_by: -1
query: {"$and":[{"config.learn.ue_internal_state_size":{"$eq":2}}]}
limit: 50

Request URL: http://127.0.0.1:11000/api/v1/Runs?distinct=omniboard.tags
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 28
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:49:16 GMT
ETag: W/"1c-Lk7d0Cw3EfQ2xAsuvSGIutz10rE"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
If-None-Match: W/"1c-Lk7d0Cw3EfQ2xAsuvSGIutz10rE"
Referer: http://127.0.0.1:11000/?selectedRows=%5B%5D
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
distinct: omniboard.tags

Request URL: http://127.0.0.1:11000/api/v1/Runs/count?query=%7B%22$and%22:[%7B%22config.learn.ue_internal_state_size%22:%7B%22$eq%22:2%7D%7D]%7D
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 13
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:49:16 GMT
ETag: W/"d-UQrxOu8hvgVhYDBF6F9qkTCN9b0"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
If-None-Match: W/"d-UQrxOu8hvgVhYDBF6F9qkTCN9b0"
Referer: http://127.0.0.1:11000/?selectedRows=%5B%5D
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
query: {"$and":[{"config.learn.ue_internal_state_size":{"$eq":2}}]}

**Network traces in the 2.8.1 version:**
Request URL: http://127.0.0.1:11000/sacred0006/api/v1/Omniboard.Metric.Columns
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 1209
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:52:44 GMT
ETag: W/"4b9-giPN6cc+volFVxHFtW2zFg8X2CU"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
If-None-Match: W/"4b9-giPN6cc+volFVxHFtW2zFg8X2CU"
Referer: http://127.0.0.1:11000/sacred0006
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

Request URL: http://127.0.0.1:11000/sacred0006/api/v1/Omniboard.Custom.Columns
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 1190
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:52:44 GMT
ETag: W/"4a6-4EfZzq5ishTVV40md3fl/U/nTkc"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
If-None-Match: W/"4a6-4EfZzq5ishTVV40md3fl/U/nTkc"
Referer: http://127.0.0.1:11000/sacred0006
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36

equest URL: http://127.0.0.1:11000/sacred0006/api/v1/Runs?select=_id,experiment.name,start_time,status,omniboard.tags,duration,result,Rval+SEM,IC,Rval+Avg+Inst,L_a+avg,Rtr+Avg+Rep0,Qmax+Mean+Last,Qmax+Inst+Mean,Qmax+Inst+Last,Rval+Max,config.env,config.learn,config.sacred,config.seed,config.experiment.n_repetitions,config.experiment.n_train_episodes,stop_time,config.tags&sort_by=_id&order_by=-1&query=%7B%22$and%22:[%7B%22config.learn.ue_internal_state_size%22:%7B%22$eq%22:2%7D%7D]%7D&limit=50
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 649
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:52:44 GMT
ETag: W/"289-NYPlLKeXUZfYWYqfhOrRwzz4hI8"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
Referer: http://127.0.0.1:11000/sacred0006
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
select: _id,experiment.name,start_time,status,omniboard.tags,duration,result,Rval SEM,IC,Rval Avg Inst,L_a avg,Rtr Avg Rep0,Qmax Mean Last,Qmax Inst Mean,Qmax Inst Last,Rval Max,config.env,config.learn,config.sacred,config.seed,config.experiment.n_repetitions,config.experiment.n_train_episodes,stop_time,config.tags
sort_by: _id
order_by: -1
query: {"$and":[{"config.learn.ue_internal_state_size":{"$eq":2}}]}
limit: 50

Request URL: http://127.0.0.1:11000/sacred0006/api/v1/Runs?distinct=omniboard.tags
Request Method: GET
Status Code: 304 Not Modified
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Content-Length: 28
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:52:45 GMT
ETag: W/"1c-Lk7d0Cw3EfQ2xAsuvSGIutz10rE"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
If-None-Match: W/"1c-Lk7d0Cw3EfQ2xAsuvSGIutz10rE"
Referer: http://127.0.0.1:11000/sacred0006
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
distinct: omniboard.tags

Request URL: http://127.0.0.1:11000/sacred0006/api/v1/Runs/count?query=%7B%22$and%22:[%7B%22config.learn.ue_internal_state_size%22:%7B%22$eq%22:2%7D%7D]%7D
Request Method: GET
Status Code: 200 OK
Remote Address: 127.0.0.1:11000
Referrer Policy: no-referrer-when-downgrade
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Methods: GET,HEAD,OPTIONS,POST,PUT,DELETE
Access-Control-Allow-Origin: *
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 13
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Apr 2020 06:52:44 GMT
ETag: W/"d-UQrxOu8hvgVhYDBF6F9qkTCN9b0"
X-Powered-By: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,es-ES;q=0.8,es;q=0.7,de-DE;q=0.6,de;q=0.5,fr;q=0.4,gl;q=0.3
Connection: keep-alive
Host: 127.0.0.1:11000
Referer: http://127.0.0.1:11000/sacred0006
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36
query: {"$and":[{"config.learn.ue_internal_state_size":{"$eq":2}}]}

**Comment by vivekratnavel** [comment]
Hi @alvarovalcarce,

Thanks for filing this issue! I was able to reproduce this bug in my local dev environment and fixed it. You should be able to update Omniboard to the next version pretty soon.
