### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by kilsenp** [vivekratnavel/omniboard#21]
When installing through npm install -g omniboard, I only get a blank screen for the latest version.
I checked @0.0.3 that still worked. From source also works.

**Comment by vivekratnavel** [comment]
This might also be associated with browser cache issue #22 . Could you please retry installing the latest version ? I tried just now and it works. It should install `omniboard@0.0.7`. If not, please let me know.

**Comment by kilsenp** [comment]
Hi.
thanks, yes, it worked after cleaning the cache through the developer tools (in chrome: DevTools -> Applications -> Clear Storage).
