### ISSUE TITLE
Blank screen on scroll and pending

### ISSUE THREAD

**Issue by MaxSchambach** [vivekratnavel/omniboard#210]
I am facing a strange yet reproducible bug with Omniboard.
Scrolling many experiments (or dragging the scrollbar with the mouse) at some point causes the Omniboard page to go totally blank (not only the table but everything). Refreshing the page brings back everything.

I have found it to be precisely reproducible, it seems to happen when Omniboard is fetching from the database (sometimes, a "PENDING" is shown in the table. When scrolling, everything turns blank). This way, I am not able to reach certain experiments by scrolling (and thus only by filtering to bring them up to the top).

I don't know how to debug this, so let me know, if I can provide any additional information that might help.

**Comment by vivekratnavel** [comment]
Hi @MaxSchambach,

Omniboard fetches the experiments lazily. Initially when the page loads, it fetches 50 experiments by default (this can be changed by editing the [settings](https://vivekratnavel.github.io/omniboard/#/usage?id=change-timezone)). When you scroll down, all the rows from the first row to the row you have scrolled gets fetched. It is expected you see "PENDING" on all cells of the table while Omniboard tries to fetch those rows from the server. 

The reason you might see a blank screen would most probably due to an error encountered while rendering the newly fetched row. To debug, can you do these 3 things?

- How many experiments do you have? You can see the count just above the table on the left side.
- Can you try in incognito window? (to make sure its not the saved settings that's causing the issue)
- Open the Developer Console (Right Click -> Inspect) in Chrome and let me know if you see any errors in the console.

**Comment by MaxSchambach** [comment]
Hi, thanks for the reply! Regarding your three points:

1. There are 90 experiments in the database.

2. The blank screen does **not** occur in incognito mode!

3. The output of the Console when the blank screen occurs reads:
```
Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Blearning_rate%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at gn (main.95f78c29.js:1)
    at main.95f78c29.js:1
    at tr (main.95f78c29.js:1)
    at Il (main.95f78c29.js:1)
    at to (main.95f78c29.js:1)
    at Qr (main.95f78c29.js:1)
    at Wr (main.95f78c29.js:1)
    at main.95f78c29.js:1
    at t.unstable_runWithPriority (main.95f78c29.js:1)
    at Wt (main.95f78c29.js:1)
```

Hope that help!

**Comment by vivekratnavel** [comment]
Ah! The console error doesn't help since the scripts are minified. But, it looks like some setting you have saved is not applicable to some of the rows. In this case, you can reset cache and try again (https://vivekratnavel.github.io/omniboard/#/troubleshooting)

**Comment by MaxSchambach** [comment]
I reset the cache and yes that solve the problem at first glance.
After playing around with the columns a little bit, I found the problem also to occur when I scroll horizontally or after deleting a couple of columns. So I guess it is associated with the columns, possibly with the custom ones? (I have some metric and some custom config columns). I cant seem to figure out which column in particular...

I went back to incognito mode and observed the same behavior there.

Is there any way I can make the console error log more helpful?
Before the error occurs, it shows the following
```
[DOM] Found 2 elements with non-unique id #react-select-2-input: (More info: https://goo.gl/9p2vKq)
```

**Comment by vivekratnavel** [comment]
Yes, you can start omniboard in dev mode by checking out omniboard source code from github and following the instructions here - https://vivekratnavel.github.io/omniboard/#/development?id=development

We will then get to know exactly which column is causing an issue. From my experience, it is usually data in one cell that does not conform to the data type that's causing the issue.

Once you found the error message in console, please post it here, so we can debug further.

**Comment by MaxSchambach** [comment]
I tried building the dev version for some time now, but can't seem to get it done.
After installing a bunch of missing dependencies by hand, it would not compile, maybe due to a newer nodejs or react version (seems to be related to [this](https://stackoverflow.com/questions/55140033/failed-to-compile-webpack-is-not-a-function))

Is there any way I can do this directly in the docker image?
Sorry, I am not really used to the nodejs universe...

**Comment by vivekratnavel** [comment]
Docker will not help since the images have minified scripts. What versions of node, npm and yarn do you have installed?

Can you try installing node v12? You can install nvm to switch between different node versions.

And then do, `yarn install`, `cd web; yarn install`

If you still see issues, please post the errors and I will help you resolve them.

**Comment by MaxSchambach** [comment]
Thanks for your patience, I am getting closer!
Using node v12 via nvm helped, I think the dev installation now works, however since I am connecting to a remote MongoDB, I am getting connection errors from the default localhost:27017 connection.
I tried setting up a omniboard.conf as suggested in the [documentation](https://vivekratnavel.github.io/omniboard/#/quick-start) however, using the exact one stated in the docs, it throws the error
```
"db1": {
     ^
SyntaxError: Unexpected token ':'
```
but maybe thats another issue. How do I set the MongoDB URI with username and password when running the dev server? (Of course I could create another local MongoDB but then I am likely not seeing the issues related to the custom or metric columns).

Sorry for all the inconvenience.

**Comment by vivekratnavel** [comment]
Great! You can start the server by running 
`yarn run server --mu mongodb://dockerhost:27019/sacred`
And then start web server in another terminal by
`cd web`
`yarn run start`

**Comment by MaxSchambach** [comment]
Ok, now to the actual error messages:
They all seem to be related to columns with config parameters that are dictionaries (which I have a couple of). Not showing the dict columns, no error is thrown (and the screen does not turn blank).
It seems to occur even if the dict config is set for all experiments (some dict configurations however are not set for all experiments). 

It seems a little strange, because I have previously seen Omniboard showing dict configuration parameters correctly...

It throws several identical error messages, the error reads (for each dictionary config parameter):

```
Uncaught Error: Objects are not valid as a React child 
(found: object with keys {<dict keys>}). If you meant to render a 
collection of children, use an array instead.
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in FixedDataTableCellDefault (created by TextCell)
    in TextCell (created by RunsTable)
    in span (created by PendingCell)
    in PendingCell (created by RunsTable)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in FixedDataTableCellDefault (created by ExpandRowCell)
    in ExpandRowCell (created by RunsTable)
    in div (created by FixedDataTableCell)
    in FixedDataTableCell (created by FixedDataTableCellGroupImpl)
    in div (created by FixedDataTableCellGroupImpl)
    in FixedDataTableCellGroupImpl (created by FixedDataTableCellGroup)
    in div (created by FixedDataTableCellGroup)
    in FixedDataTableCellGroup (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in FixedDataTableRowImpl (created by FixedDataTableRow)
    in div (created by FixedDataTableRow)
    in FixedDataTableRow (created by FixedDataTableBufferedRows)
    in div (created by FixedDataTableBufferedRows)
    in FixedDataTableBufferedRows (created by FixedDataTable)
    in div (created by FixedDataTable)
    in div (created by FixedDataTable)
    in FixedDataTable (created by FixedDataTableContainer)
    in FixedDataTableContainer (created by RunsTable)
    in ProgressWrapper (created by RunsTable)
    in div (created by RunsTable)
    in div (created by RunsTable)
    in RunsTable (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Route)
    in Route (created by Routes)
    in Switch (created by Routes)
    in div (created by Routes)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Routes)
    in Routes (created by HotExportedRoutes)
    in AppContainer (created by HotExportedRoutes)
    in HotExportedRoutes
    at throwOnInvalidObjectType (react-dom.development.js:13436)
    at reconcileChildFibers (react-dom.development.js:14336)
    at reconcileChildren (react-dom.development.js:16787)
    at updateHostComponent (react-dom.development.js:17327)
    at beginWork (react-dom.development.js:18661)
    at HTMLUnknownElement.callCallback (react-dom.development.js:189)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:238)
    at invokeGuardedCallback (react-dom.development.js:293)
    at beginWork$1 (react-dom.development.js:23235)
    at performUnitOfWork (react-dom.development.js:22189)
    at workLoopSync (react-dom.development.js:22162)
    at performSyncWorkOnRoot (react-dom.development.js:21788)
    at react-dom.development.js:11112
    at unstable_runWithPriority (scheduler.development.js:653)
    at runWithPriority$1 (react-dom.development.js:11062)
    at flushSyncCallbackQueueImpl (react-dom.development.js:11107)
    at flushSyncCallbackQueue (react-dom.development.js:11095)
    at scheduleUpdateOnFiber (react-dom.development.js:21231)
    at Object.enqueueSetState (react-dom.development.js:12662)
    at FixedDataTableContainer../node_modules/react/cjs/react.development.js.Component.setState (react.development.js:471)
    at FixedDataTableContainer.update (FixedDataTableContainer.js:112)
    at FixedDataTableContainer.update (react-hot-loader.development.js:714)
    at dispatch (redux.js:214)
    at Object.scrollToX (redux.js:462)
    at Object.onScroll (FixedDataTable.js:415)
    at Scrollbar._setNextState (Scrollbar.js:417)
    at DOMMouseMoveTracker._onMove (Scrollbar.js:268)
    at DOMMouseMoveTracker._didMouseMove (DOMMouseMoveTracker.js:199)


 index.js:2177 
The above error occurred in the <div> component:              
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in FixedDataTableCellDefault (created by TextCell)
    in TextCell (created by RunsTable)
    in span (created by PendingCell)
    in PendingCell (created by RunsTable)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in div (created by FixedDataTableCellDefault)
    in FixedDataTableCellDefault (created by ExpandRowCell)
    in ExpandRowCell (created by RunsTable)
    in div (created by FixedDataTableCell)
    in FixedDataTableCell (created by FixedDataTableCellGroupImpl)
    in div (created by FixedDataTableCellGroupImpl)
    in FixedDataTableCellGroupImpl (created by FixedDataTableCellGroup)
    in div (created by FixedDataTableCellGroup)
    in FixedDataTableCellGroup (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in div (created by FixedDataTableRowImpl)
    in FixedDataTableRowImpl (created by FixedDataTableRow)
    in div (created by FixedDataTableRow)
    in FixedDataTableRow (created by FixedDataTableBufferedRows)
    in div (created by FixedDataTableBufferedRows)
    in FixedDataTableBufferedRows (created by FixedDataTable)
    in div (created by FixedDataTable)
    in div (created by FixedDataTable)
    in FixedDataTable (created by FixedDataTableContainer)
    in FixedDataTableContainer (created by RunsTable)
    in ProgressWrapper (created by RunsTable)
    in div (created by RunsTable)
    in div (created by RunsTable)
    in RunsTable (created by App)
    in div (created by App)
    in div (created by App)
    in App (created by Route)
    in Route (created by Routes)
    in Switch (created by Routes)
    in div (created by Routes)
    in Router (created by BrowserRouter)
    in BrowserRouter (created by Routes)
    in Routes (created by HotExportedRoutes)
    in AppContainer (created by HotExportedRoutes)
    in HotExportedRoutes

React will try to recreate this component tree from scratch using the error boundary you provided, AppContainer.
```

**Comment by vivekratnavel** [comment]
I have a similar custom column with dictionary as value, but I am not able to reproduce the issue.

<img width="275" alt="Screen Shot 2020-04-29 at 1 20 21 AM" src="https://user-images.githubusercontent.com/1051198/80575131-e14a8800-89b7-11ea-8304-65ba024be571.png">


Can you give more details on the structure of this dictionary? Also, can you verify if these console errors are logged only when a few experiment runs are being displayed? You can do this by applying filter on id column to display only 10 rows at a time to narrow down the runs with issues.

**Comment by MaxSchambach** [comment]
It does not happen, when there are only a few experiments to show, e.g. by filtering.

I think it is related to the dynamic fetching. When I filter by one experiment that has less then the amount of rows that are fetched by default, i.e. everything is fetched, the error does not occur and the dictionaries are shown just as in the screen shot you posted.
When I set the numbers of rows fetched below the number of experiments to currently show (and still being able to scroll to induce fetching), the error occurs.

**Comment by MaxSchambach** [comment]
@vivekratnavel Were you able to reproduce the issue? Is there anything further that I can provide?

**Comment by vivekratnavel** [comment]
Hi @MaxSchambach,

Sorry for getting back late on this. I got busy with other projects lately. Your detailed analysis helped me reproduce this issue in my local environment. I will work on a fix soon. Thanks!

**Comment by vivekratnavel** [comment]
@MaxSchambach, please let me know if this patch fixes the error. Hopefully, it does :)

**Comment by MaxSchambach** [comment]
Hi, no problem!
Yes, I can confirm, with version 2.8.5 the issue seems to be fixed.
Thanks!
