### ISSUE TITLE
Experiment name not displayed unless browser's local storage with key path|RunsTable|1 is deleted

### ISSUE THREAD

**Issue by alvarovalcarce** [vivekratnavel/omniboard#213]
I noticed that Omniboard does not display the experiment name after refreshing the page.
However, it is displayed after deleting the site's local storage of the browser. The experiment name then vanishes again after the first page reload. I have seen this behaviour in Firefox and Chrome in Windows.

In Chrome, for instance, the workaround to display the experiment name again is as follows:
-On the Omniboard website, click F12 to open the DevTools panel.
-Click the "Application" tab on the upper bar.
-Click the "Local Storage" item on the left panel.
-Click on the Omniboard URL.
-Click on "path|RunsTable|1" in the Key column.
-Press "Delete" to delete the entry

Any idea of why this may be?

**Comment by vivekratnavel** [comment]
@alvarovalcarce  Can you please paste the value of path|RunsTable|1 before deleting it?

**Comment by alvarovalcarce** [comment]
{
   "dropdownOptions":[
      {
         "label":" Id",
         "value":"_id",
         "selected":true
      },
      {
         "label":"Experiment Name",
         "value":"experiment_name",
         "selected":true
      },
      {
         "label":"Hostname",
         "value":"hostname",
         "selected":true
      },
      {
         "label":"Format",
         "value":"format",
         "selected":true
      },
      {
         "label":"Command",
         "value":"command",
         "selected":true
      },
      {
         "label":"Start Time",
         "value":"start_time",
         "selected":true
      },
      {
         "label":"Status",
         "value":"status",
         "selected":true
      },
      {
         "label":"Tags",
         "value":"tags",
         "selected":true
      },
      {
         "label":"Notes",
         "value":"notes",
         "selected":true
      },
      {
         "label":"Resources",
         "value":"resources",
         "selected":true
      },
      {
         "label":"Heartbeat",
         "value":"heartbeat",
         "selected":true
      },
      {
         "label":"Duration",
         "value":"duration",
         "selected":true
      },
      {
         "label":"Result",
         "value":"result",
         "selected":true
      },
      {
         "label":"Stop Time",
         "value":"stop_time",
         "selected":true
      },
      {
         "label":"SINR SEM",
         "value":"SINR SEM",
         "selected":true
      },
      {
         "label":"Dur",
         "value":"Dur",
         "selected":true
      },
      {
         "label":"Plot",
         "value":"plot",
         "selected":true
      },
      {
         "label":"Seed",
         "value":"seed",
         "selected":true
      },
      {
         "label":"Sacred",
         "value":"sacred",
         "selected":true
      },
      {
         "label":"N",
         "value":"N",
         "selected":true
      },
      {
         "label":"Param",
         "value":"Param",
         "selected":true
      },
      {
         "label":"Test cell",
         "value":"Test cell",
         "selected":true
      },
      {
         "label":"Fairness",
         "value":"fairness",
         "selected":true
      },
      {
         "label":"CPUs",
         "value":"CPUs",
         "selected":true
      },
      {
         "label":"Got Gizmo",
         "value":"got_gizmo",
         "selected":true
      },
      {
         "label":"Number",
         "value":"number",
         "selected":true
      }
   ],
   "columnOrder":[
      "_id",
      "experiment_name",
      "hostname",
      "format",
      "command",
      "start_time",
      "status",
      "tags",
      "notes",
      "resources",
      "heartbeat",
      "duration",
      "result",
      "stop_time",
      "SINR SEM",
      "Dur",
      "plot",
      "seed",
      "sacred",
      "N",
      "Param",
      "Test cell",
      "fairness",
      "CPUs",
      "got_gizmo",
      "number"
   ],
   "columnWidths":{
      "_id":70,
      "experiment_name":150,
      "hostname":150,
      "format":150,
      "command":150,
      "start_time":150,
      "status":150,
      "tags":250,
      "notes":250,
      "resources":150,
      "heartbeat":150,
      "duration":150,
      "result":150,
      "stop_time":150,
      "SINR SEM":150,
      "Dur":150,
      "plot":150,
      "seed":150,
      "sacred":150,
      "N":150,
      "Param":150,
      "Test cell":150,
      "fairness":150,
      "CPUs":150,
      "got_gizmo":150,
      "number":150
   },
   "sort":{

   },
   "metricAndCustomColumns":[
      {
         "name":"SINR SEM",
         "value":"SINR SEM"
      },
      {
         "name":"Dur",
         "value":"Dur"
      },
      {
         "name":"N",
         "value":"config.experiment.num_samples"
      },
      {
         "name":"Param",
         "value":"config.experiment.test_param"
      },
      {
         "name":"Test cell",
         "value":"config.experiment.test_cells"
      },
      {
         "name":"fairness",
         "value":"config.experiment.fairness"
      },
      {
         "name":"CPUs",
         "value":"config.experiment.n_proc"
      }
   ],
   "columnNameMap":{
      "experiment":"config.experiment",
      "plot":"config.plot",
      "seed":"config.seed",
      "sacred":"config.sacred",
      "N":"config.experiment.num_samples",
      "Param":"config.experiment.test_param",
      "Test cell":"config.experiment.test_cells",
      "fairness":"config.experiment.fairness",
      "CPUs":"config.experiment.n_proc",
      "experiment_name":"experiment.name",
      "hostname":"host.hostname",
      "os":"host.os",
      "python_version":"host.python_version",
      "cpu":"host.cpu",
      "gpus":"host.gpus",
      "ENV":"host.ENV",
      "tags":"omniboard.tags",
      "notes":"omniboard.notes",
      "got_gizmo":"config.got_gizmo",
      "number":"config.number"
   },
   "statusFilterOptions":[
      {
         "label":"<div class=\"clearfix\">\n            <div class=\"circle running pull-left\"></div>\n            <div class=\"status-text pull-left\">Running</div>\n          </div>",
         "value":"RUNNING",
         "selected":true
      },
      {
         "label":"<div class=\"clearfix\">\n            <div class=\"circle completed pull-left\"></div>\n            <div class=\"status-text pull-left\">Completed</div>\n          </div>",
         "value":"COMPLETED",
         "selected":true
      },
      {
         "label":"<div class=\"clearfix\">\n            <div class=\"circle failed pull-left\"></div>\n            <div class=\"status-text pull-left\">Failed</div>\n          </div>",
         "value":"FAILED",
         "selected":true
      },
      {
         "label":"<div class=\"clearfix\">\n            <div class=\"circle interrupted pull-left\"></div>\n            <div class=\"status-text pull-left\">Interrupted</div>\n          </div>",
         "value":"INTERRUPTED",
         "selected":true
      },
      {
         "label":"<div class=\"clearfix\">\n            <div class=\"circle timeout pull-left\"></div>\n            <div class=\"status-text pull-left\">Timeout</div>\n          </div>",
         "value":"TIMEOUT",
         "selected":true
      },
      {
         "label":"<div class=\"clearfix\">\n            <div class=\"circle probably_dead pull-left\"></div>\n            <div class=\"status-text pull-left\">Probably Dead</div>\n          </div>",
         "value":"PROBABLY_DEAD",
         "selected":true
      },
      {
         "label":"<div class=\"clearfix\">\n            <div class=\"circle queued pull-left\"></div>\n            <div class=\"status-text pull-left\">Queued</div>\n          </div>",
         "value":"QUEUED",
         "selected":true
      }
   ],
   "filters":{
      "status":[

      ],
      "advanced":[

      ]
   },
   "autoRefresh":true
}

**Comment by vivekratnavel** [comment]
@alvarovalcarce  Do you have a custom column with the name "experiment" that maps to "config.experiment"?
I can see this under columnNameMap which is my first suspicion:
`"experiment":"config.experiment"`

By default, "experiment_name" is mapped to "experiment.name", but with the above mapping, "experiment_name" would be pointing to "config.experiment.name" and might cause undesired results.

Can you rename your custom column name to "exp" or something other than "experiment" and try again? Thanks!

**Comment by alvarovalcarce** [comment]
Hi  @vivekratnavel .
I see the column name mapping. But I do not have such a custom column with name "experiment", so I can't explain where this mapping leaks into columnMapOrder.

I've renamed it to "exp2" in the DevTools. But it is restored to the "experiment" name after the first page refresh.
I've noticed that columnMapOrder also contains other column names that I never configured and that are not rendered in the HTML. These are os, ENV, got_gizmo and python_version. Where do these come from?

**Comment by vivekratnavel** [comment]
Ah, I got it. It's coming from "config". It seems like you have "experiment" under "config" which conflicts with the "experiment" at root, since Omniboard tries to expand all the first level configs into a new column automatically. If you rename "config.experiment", everything should work fine.

**Comment by alvarovalcarce** [comment]
I see. Thanks @vivekratnavel . I will rename config.experiment going forward. Unfortunately, I've got hundreds of experiments with that configuration name...

**Comment by vivekratnavel** [comment]
@alvarovalcarce I am working on a patch to avoid these conflicts in the future. The patch will add a prefix "c_" for columns expanded from config. Once that patch is out, you will not need to update your hundreds of experiments and continue to use the same configs.

**Comment by vivekratnavel** [comment]
This issue should now be fixed. Please try to clear your browser's local storage one last time and try the latest version of Omniboard and let me know if it works. Thanks!

**Comment by alvarovalcarce** [comment]
It works! Thanks @vivekratnavel .
You're on fire these days. Keep it up!
