### ISSUE TITLE
Console Log Leaks Mongo Credentials

### ISSUE THREAD

**Issue by isugimpy** [vivekratnavel/omniboard#215]
Currently, when either connecting successfully or failing to connect, a console.log statement prints the URI to connect to Mongo in plaintext.  This leaks the connection credentials in a way which may be harmful.  At the very least, the username and password should be obfuscated, if not completely removed from the log message.

**Comment by vivekratnavel** [comment]
#214 fixes this

**Comment by isugimpy** [comment]
@vivekratnavel That fixes one instance of it, but it's also leaked in two places in https://github.com/vivekratnavel/omniboard/blob/master/server/config/database.js

**Comment by vivekratnavel** [comment]
@isugimpy Thanks for pointing out! I will fix it soon.
