### ISSUE TITLE
Feature request: Config values in compare plot legend

### ISSUE THREAD

**Issue by MaxSchambach** [vivekratnavel/omniboard#216]
I have mentioned this in the closed issue #180 :
While this one has been closed and it now possible to use the Experiment Name as the plot label, this does not fully work for many workflows (including mine, obviously).

I often use the Experiment Name to group single runs with a common experiment target. Then, when comparing many runs, the ID is not very informative (as mentioned in #180 ) and the Experiment Name is not necessarily unique.

What I would suggest is to make it possible to add arbitrary (possibly multiple, concatenated) configuration parameters to the label.
This would make it very straightforward to compare different configuration hyperparameters, such as different model topologies, used optimizers, batch sizes (in case of ML) and so on. For me, this would be a huge improvement when evaluating experiments with Omniboard! (Otherwise, I am, too, really enjoying working with Omniboard, it's a super useful tool!)

Ideally, there would be some sort of 'plus buttom' to concatenate legend label strings with arbitrary configuration parameters. I have tried fiddling around with the corresponding JavaScript files, however my JavaScript skills are virtually non-existent, so I failed and unfortunately can't help with a pull request.

**Comment by vivekratnavel** [comment]
<img width="1822" alt="Screen Shot 2020-05-28 at 1 37 11 AM" src="https://user-images.githubusercontent.com/1051198/83124079-9725f680-a08a-11ea-8a8f-f57299995a8a.png">

You can now add multiple metric labels with a wide range of options to choose from the dropdown. 

@MaxSchambach Let me know how you like the new feature. Thanks!

**Comment by MaxSchambach** [comment]
Very cool, thanks!
Just tried it out, pretty much exactly what I thought it could work like.
Thank you for the super quick implementation!

**Comment by vivekratnavel** [comment]
@MaxSchambach Thanks for your UI design idea! It helped me to quickly implement the feature. Thanks for trying out quickly and I am glad it works for you!

**Comment by alvarovalcarce** [comment]
Are some type of configuration parameter excluded from the dropdown list?
I have some configuration parameters in the form of a list that don't show up here.

**Comment by vivekratnavel** [comment]
@alvarovalcarce Yes, only strings are shown. If it is a dictionary, it will get expanded.
