### ISSUE TITLE
Error when trying to download all artifacts

### ISSUE THREAD

**Issue by alpapado** [vivekratnavel/omniboard#217]
Hello.

When visiting the artifacts tab for a run, omniboard shows an _Error:undefined_. Yet, it correctly shows all the artifacts (around 210) and I can download each one separately.

When trying to download all the artifacts using the _Download All_ button, I get an _Error: No files are available to download_ (again it correctly shows the artifact list and I can download each artifact separately). 

In the browser console I get the following errors  
![image](https://user-images.githubusercontent.com/11426919/83243206-42779e00-a1a6-11ea-9592-1ba81440b306.png)

I use omniboard v2.12.0 but it also happened in previous versions  (I think v2.8)

**Comment by vivekratnavel** [comment]
@alpapado I think it might be because of the large number of artifacts. Can you post any error messages that you see in the server log when you click "Download All" button?

**Comment by alpapado** [comment]
I get no error in the server log (see attached output file). 
Regarding the console error I get the error in the screenshot of my previous message.
Regarding the requests in the network tab, there are a lot of requests but I think the attached request file is what we are looking for

[out.log](https://github.com/vivekratnavel/omniboard/files/4723557/out.log)
[request.log](https://github.com/vivekratnavel/omniboard/files/4723558/request.log)

**Comment by vivekratnavel** [comment]
@alpapado Try out the latest version of Omniboard and you should be able to download all the artifacts.
