### ISSUE TITLE
Config not shown

### ISSUE THREAD

**Issue by kilsenp** [vivekratnavel/omniboard#22]
Hi, 
thanks for you work. Looks pretty cool so far.
When looking at my experiments, I cannot see my configuration at all which I think is quite odd because I would assume that this is a basic feature Omniboard probably supports.

And how do I get additional columns to show up like seen in your screenshot ('Optimizer name', 'BatchNorm' etc). I'm kind of guessing that this is related to my config not showing up.

**Comment by vivekratnavel** [comment]
Hi @kilsenp,

Thanks for trying out Omniboard! Could you please try clearing your browser cache or open an incognito window and try?

Expected behavior is that all the configs should show up as individual columns as seen in the screenshot.

**Comment by kilsenp** [comment]
Thanks for the quick response. Yes, that did the job!
