### ISSUE TITLE
Feature request: Enable height-adjustment of the expanded experiment row

### ISSUE THREAD

**Issue by alvarovalcarce** [vivekratnavel/omniboard#222]
I usually view artifact figures in the expanded experiment row (the one that unfolds when clicking on the downwards pointing arrow). However, my figures are usually large so the fixed height of this panel blocks most of it. Could this panel perhaps be resizable in height?

**Comment by vivekratnavel** [comment]
Hi @alvarovalcarce,

This is related to the feature request in #248. With the latest release, you should see an option to expand this drill-down view to a full-screen modal dialog.
