### ISSUE TITLE
Source file comparison not working in chrome for windows

### ISSUE THREAD

**Issue by bbeniamin** [vivekratnavel/omniboard#224]
I'm using Omniboard v2.8.3 for visualizing some experiments (tracked by sacred and stored in mongodb). For some reason the source file diff feature in the comparison dialog never worked for me.  I tried it in Chrome (83.0.4103.97), Firefox & Edge (some slightly older versions) and Chromium (latest build, downloaded today), but the feature doesn't work in either of them. 

With Chrome I get the following error twice whenever I open the "source file" menu in the comparison dialog:
`Uncaught (in promise) TypeError: Failed to execute 'decode' on 'TextDecoder': The provided value is not of type '(ArrayBuffer or ArrayBufferView)'
    at i (main.ab96bd07.js:1)
    at e (main.ab96bd07.js:1)`

**Comment by janstrohbeck** [comment]
I got the same error message, and for me it was fixed by #240.
