### ISSUE TITLE
Feature Request: Read-only mode

### ISSUE THREAD

**Issue by leogao2** [vivekratnavel/omniboard#229]
It would be great to be able to start omniboard in a read-only mode where editing notes, delete, etc are disabled. It would be useful for exposing dashboards to the outside world.

**Comment by MaxSchambach** [comment]
When you have access to the used MongoDB setup, you can simply add a user with only read permissions:

```
use admin
db.createUser(
{
  user: "<username>",
  pwd: passwordPrompt(),  // Or  "<cleartext password>"
  customData: { "name": "Firstname Lastname" },
  roles: [ { role: "read", db: "<SacredDatabaseName>" }],  // Possibly add more roles
  mechanisms: ["SCRAM-SHA-256"]  // Or  "SCRAM-SHA-1"
}
)
```

and then use Omniboard with the specified user.

**Comment by vivekratnavel** [comment]
Closing this issue since there is a simple workaround as mentioned by @MaxSchambach.
