### ISSUE TITLE
will delete in omniboard also delete the files in mongodb?

### ISSUE THREAD

**Issue by Guptajakala** [vivekratnavel/omniboard#236]
Hi, thanks for this great work, I really love it!
One quesion is will delete in omniboard also delete the files in mongodb? As I had more experiments the database becomes bigger and I wanted to do some cleanup. I deleted some experiments in omniboard but I found the database size is not changed.

For example, if my database name is "sacred",
```
> show dbs
sacred  165.679GB
```

This is the same before and after I delete some experiments in omniboard.

**Comment by vivekratnavel** [comment]
Hi @Guptajakala, 

Sacred uses references to store files for each experiment. For instance, multiple experiment runs can share the same files if there were no changes made to the source code. For this reason, Omniboard will not delete files/artifacts unless the experiment being deleted is the only one that references those files. 

You will not see any big change in the db size until you delete all experiments that share the same set of files. 
  
https://github.com/vivekratnavel/omniboard/issues/182
https://github.com/vivekratnavel/omniboard/issues/153
