### ISSUE TITLE
Feature Request: Tag multiple experiments

### ISSUE THREAD

**Issue by Kotzly** [vivekratnavel/omniboard#245]
I often run multiple experiments but with little modifications. When they are finished, I am left with 10-20 experiments that I will have to manually add the same 3 or 4 tags to all of them. It would be nice if it was possible to add tags in various experiments (by selecting them) at the same time.

**Comment by vivekratnavel** [comment]
Hi @Kotzly, 

Thanks for using Omniboard! For this use-case, you can add tags to the experiments in sacred - https://vivekratnavel.github.io/omniboard/#/usage?id=add-tags-using-configs

Let me know if this is what you needed.

**Comment by Kotzly** [comment]
That solves my problem, thank you very much!
