### ISSUE TITLE
Feature Request: Open new page instead of expand when we click a experiment.

### ISSUE THREAD

**Issue by Haetsal-Lee** [vivekratnavel/omniboard#248]
It would be great to make option "open experiment in the new page when click".

In my case, when Omniboard shows detailed information of a experiment, the space is to narrow that it's difficult to navigate source codes. 

I think the simple solution would be just open it in new page.

Another expected good side-effect with this feature is that "it will make us to switch between multiple detailed experiment information"

* I think many of us have a experience of using web-apps working like this.  And many old style BBS display article like this. right?

**Comment by komodovaran** [comment]
Or simply increase the size of the `<div class="tab-content">` and I'd still be happy.

**Comment by vivekratnavel** [comment]
I added a feature to expand the drill-down view to a full-screen modal dialog. You just have to click on the title of the drill-down view as shown in the screenshot below:
<img width="230" alt="Screen Shot 2021-07-11 at 4 27 27 AM" src="https://user-images.githubusercontent.com/1051198/125193254-5cd0d780-e200-11eb-84d9-a52fb0f18636.png">

@Haetsal-Lee @komodovaran Check it out and let me know how you like it :)

**Comment by Haetsal-Lee** [comment]
Wow! I like this feature.

I imagined to have a switch option toggling between full-screen and drill-down. But this looks working much better in terms of UX.

Thank you for your effort @vivekratnavel .

**Comment by vivekratnavel** [comment]
@Haetsal-Lee This feature also supports sharing the URL. After you open any experiment in full-screen mode, you can share the URL or  open a new tab to load the details in full-screen mode.
