### ISSUE TITLE
Q&A doc: How to add val_loss column?

### ISSUE THREAD

**Issue by Apollo1840** [vivekratnavel/omniboard#251]
- where to store val_loss in sacred ex
- How to add such a column to show this metric on omniboard

I tried:

     ex.info["val_loss"] = val_loss

Those two do not solve my problem:
https://github.com/vivekratnavel/omniboard/blob/master/docs/usage.md
https://vivekratnavel.github.io/omniboard/#/quick-start?id=custom-columns

**Comment by Apollo1840** [comment]
@vivekratnavel please help me, thanks a lot!

**Comment by vivekratnavel** [comment]
Did you try `info.val_loss` for custom column?

**Comment by Apollo1840** [comment]
> Did you try `info.val_loss` for custom column?

Thanks, it works! Simple as it is.

So that input box is not select only ...

**Comment by vivekratnavel** [comment]
@Apollo1840 I am glad it worked. Yes, it can take any input for a custom column.
