### ISSUE TITLE
Feature Request: Average the last n metrics

### ISSUE THREAD

**Issue by kkoutini** [vivekratnavel/omniboard#256]
In my case, the testing metric is a bit noisy, therefore having a metrics column with "last" extrema is not reliable. I think having the option to average the last n values of a metric can be useful.

**Comment by kkoutini** [comment]
I made  an example for averaging the last `10` values [here](https://github.com/kkoutini/omniboard/commit/7f29828e9cd4533adbb7755429da99b7e3571728), is there any recommendations to allow the user to specify how many values to average. is there a good place for this? like a setting or env variable?

**Comment by vivekratnavel** [comment]
Hi @kkoutini,

Thanks for the request and example. I think you are almost there. We can show a small text box to get "n" as input from the user. This text box should be visible only when "last_n_avg" extrema is selected from the extrema dropdown. We can then pass that "n" to the backend to update the query accordingly.

**Comment by kkoutini** [comment]
Hi, thanks for the response. I've added a new column and the text box  [here](https://github.com/kkoutini/omniboard/commit/74111e5eff3d40e9f9c36c53b1d8d4086dc285e9). I had to do some changes to the UI, in order to fit the new text box (changing `col-xs-4` to `col-xs-3`). I'm also not sure about the naming `Last N`.
![image](https://user-images.githubusercontent.com/51880718/115394205-d6998c00-a1e2-11eb-9593-73f15a81dbf0.png)

**Comment by vivekratnavel** [comment]
@kkoutini It looks good to me. We can label the extrema as "last N average". I am fine with "Last N" for the input field. Can you please raise a pull request?

**Comment by vivekratnavel** [comment]
Merged via #258

**Comment by vivekratnavel** [comment]
https://github.com/vivekratnavel/omniboard/pull/258#issuecomment-825854694
