### ISSUE TITLE
Improving metrics plot

### ISSUE THREAD

**Issue by MaxSchambach** [vivekratnavel/omniboard#266]
# Description
I have been using Omniboard for a while now and find it very useful. However, one thing that has been bothering me are some details related to the metrics plot. They become especially visible when comparing multiple runs:

  - The plot color cycle seems weird as it repeats green very early on or the two different greens are extremely close (for both single metrics plot and compare metrics plot)
  - Metrics from the same experiment are differently colored
  - Plots are incorrectly joined when not explicitly sorting by id, see #218 
 
To illustrate the first two points, see this example:
![metrics_plot](https://user-images.githubusercontent.com/28300359/119494729-ebc58580-bd61-11eb-80cf-b1c74eeabb31.png)

# Possible solution
  - Alter the color cycle such that there is more contrast in the first colors, or is this a request better put with plotly?
  - Use the same color for different runs in the compare metrics view but different markers or linestyles (e.g. circles, diamonds, etc .or dashed and dotted lines).
  - Possibly group the legend by run id

**Comment by vivekratnavel** [comment]
Hi @MaxSchambach ,

It is easy to change the colors used in the metrics plot. https://github.com/vivekratnavel/omniboard/blob/master/web/src/components/MetricsPlotView/metricsPlotView.js#L200

I would be happy to accept a pull request if you can come up with good contrasting color codes.

**Comment by avalcarce** [comment]
For some reason, the Docker "latest" tag is stuck at version 2.15...

**Comment by vivekratnavel** [comment]
I think it is because Docker stopped Automated builds for personal accounts. It is now a paid feature and I am trying to apply for their open-source community membership to see if they can enable automated builds for Omniboard again. 

@avalcarce Thanks for letting me know.
