### ISSUE TITLE
Plots are very small

### ISSUE THREAD

**Issue by wjaskowski** [vivekratnavel/omniboard#30]
Any changes for a configuring the size of the metric plots, which are currently very small?

**Comment by vivekratnavel** [comment]
Working on it

**Comment by vivekratnavel** [comment]
Added plot size sliders to adjust width and height of the plot

<img width="179" alt="screen shot 2018-12-31 at 4 32 44 pm" src="https://user-images.githubusercontent.com/1051198/50569431-db885800-0d19-11e9-88c1-e652bf642731.png">

**Comment by wjaskowski** [comment]
You are quick! Thanks!
