### ISSUE TITLE
Use different ports

### ISSUE THREAD

**Issue by wjaskowski** [vivekratnavel/omniboard#31]
Currently, Omniboard always uses port 9000, so I cannot run two instances of it. The desired behaviour: try other ports until found an available one.

**Comment by wjaskowski** [comment]
Indeed but don't you think using a docker for such a simple feature is an
overkill?

**Comment by widssaguenay** [comment]
If omniboard connects to a new port, let's say 9001, to a specific mongodb database, let's say sacred, then why doesn't it show any of my past experiments which were logged to the same db (when I was running those past experiments, omniboard was listening to port 9000)?
