### ISSUE TITLE
Make omniboard work with FileStorageObserver?

### ISSUE THREAD

**Issue by rajatvd** [vivekratnavel/omniboard#34]
It would be really convenient if omniboard could also work with the FileStorage backend of sacred as I have a bunch of older runs which use the FileStorageObserver. I think the file-based storage stores the same information as the MongoDB observer so it should theoretically be possible.

**Comment by vivekratnavel** [comment]
Won't be implementing this anytime sooner since it will take a lot of effort to support FileStorageObserver. Also because it doesn't make sense to spend a lot of time for a feature that has very less users, I am closing this now.

**Comment by rajatvd** [comment]
Okay, are you aware of any scripts which can copy a bunch of experiments stored in file storage format to a mongo DB? That's one tool which might be useful.
