### ISSUE TITLE
Delete associated artifacts and metrics data while deleting a run

### ISSUE THREAD

**Issue by vivekratnavel** [vivekratnavel/omniboard#37]
Currently, when an experiment run is deleted, only the run detail is deleted from the database. It should also delete all the associated artifacts and metric data

**Comment by Haetsal-Lee** [comment]
@vivekratnavel  Currently, it does not delete associated source files (.py files)

**Comment by vivekratnavel** [comment]
@Haetsal-Lee I would be happy to accept PR

**Comment by vivekratnavel** [comment]
Created #97 to track this issue
