### ISSUE TITLE
Add tags for running experiment

### ISSUE THREAD

**Issue by khaledvic** [vivekratnavel/omniboard#39]
If you add a tag to a running experiment.
it seems that the tag is getting removed after a while (maybe after the next heartbeat, after refreshing the webpage)

**Comment by kilsenp** [comment]
The same is true for comments.

**Comment by vivekratnavel** [comment]
@khaledvic @kilsenp Thanks for filing this! I looked into this issue and found out that sacred rewrites the whole record after a run completes and hence deleting the keys omniboard created when it was in `running` state. 

To fix this issue, I am thinking of moving the `tags` and `notes` out of the `runs` collection to a new collection, so that sacred won't be able to rewrite those records. But, it will be a breaking change and old notes and tags will not be available.

cc @u39kun

**Comment by kilsenp** [comment]
Alternatively, create a pull request in sacred to change the behaviour to update the record. I will try to take a look into that by next week.

**Comment by kilsenp** [comment]
Had a quick glance, if in this this line
https://github.com/IDSIA/sacred/blob/master/sacred/observers/mongo.py#L273

` self.runs.replace_one({'_id': self.run_entry['_id']}, self.run_entry)`

Was replaced by something like
` self.runs.update_one({'_id': self.run_entry['_id']}, self.run_entry)`

This might already be it, but do not have the time to test it right now.
http://api.mongodb.com/python/current/api/pymongo/collection.html
_update_one(filter, update, upsert=False, bypass_document_validation=False, collation=None, array_filters=None, session=None)
Update a single document matching the filter._

**Comment by vivekratnavel** [comment]
@kilsenp Thanks for digging into this! I tested your suggestion, but unfortunately it doesn't work. First of all, `captured_out` did not get updated. And second thing was that, it ultimately removed `tags` and `notes` from the run once it completed. 

If you want to test it, you can use my fork - https://github.com/vivekratnavel/sacred

`pip install -e git+https://github.com/vivekratnavel/sacred.git#egg=sacred`

**Comment by kilsenp** [comment]
Yes, thanks for testing. The update call was not exactly right, but now it is working for me. 
I haven't spent any time that those calls work in every edge case, for example when for some reason no record has been created yet. I only tested the cases that the run was interrupted or finished, both worked just fine.
I created a pull request, but the repo seems quite inactive. So I don't know how fast this and if at all it would be merged into the master branch. So @khaledvic you should also make those changes manually or use my branch (dev/mongo).

**Comment by khaledvic** [comment]
Thank this seems to solve the problem!

> Yes, thanks for testing. The update call was not exactly right, but now it is working for me.
> I haven't spent any time that those calls work in every edge case, for example when for some reason no record has been created yet. I only tested the cases that the run was interrupted or finished, both worked just fine.
> I created a pull request, but the repo seems quite inactive. So I don't know how fast this and if at all it would be merged into the master branch. So @khaledvic you should also make those changes manually or use my branch (dev/mongo).

**Comment by kilsenp** [comment]
The change got merged to sacred today.
