### ISSUE TITLE
Use pretty-ms instead of ms

### ISSUE THREAD

**Issue by kilsenp** [vivekratnavel/omniboard#44]
The duration is displayed quite imprecisely (if experiment takes hours, the minutes are cut off). 

I saw that this has to do with the ms package. There exists an alternative called pretty-ms. Could this be used instead?
https://www.npmjs.com/package/pretty-ms

Best regards

**Comment by vivekratnavel** [comment]
`pretty-ms` uses ES6 and breaks the build. Will bring it back after supporting ES6 for third party modules in webpack config. Currently javascript heap runs out of memory trying to compile ES6 from third party scripts.

**Comment by vivekratnavel** [comment]
Omniboard v2.0 will use pretty-ms for duration. #107

**Comment by vivekratnavel** [comment]
Omniboard v2.0.0-beta is out. You can try it out with either npm or docker - https://www.npmjs.com/package/omniboard/v/2.0.0-beta.2 
Docker image - vivekratnavel/omniboard:beta
Source code is in branch 'beta' - https://github.com/vivekratnavel/omniboard/tree/beta

Please try it out and give feedback.
