### ISSUE TITLE
Code browsing

### ISSUE THREAD

**Issue by kilsenp** [vivekratnavel/omniboard#45]
It would be quite convenient to be able to quickly browse the code to fully understand the experiment.
Currently, you have to first download the file before you can open it. It would be more convenient if it was additionally possible to just open the file in a new tab without having it to download it first.

**Comment by vivekratnavel** [comment]
@kilsenp If you want to browse the source code, it is already available when you click on a specific file from the list of source files:

<img width="1425" alt="screen shot 2019-01-16 at 6 38 57 pm" src="https://user-images.githubusercontent.com/1051198/51289629-2c58ab80-19be-11e9-81b2-1360499f0bb6.png">

Let me know, if it doesn't work for you

**Comment by kilsenp** [comment]
Ah okay, then there seems to be a bug for me.
There is an error message thrown (see attached screenshot).
![screenshot from 2019-01-17 11-28-31](https://user-images.githubusercontent.com/5173119/51312316-455b6e00-1a4b-11e9-8a7d-a56ead994b0e.png)

I am not sure how I can help you to debug it, if there is anything I can do, let me know!

**Comment by vivekratnavel** [comment]
@kilsenp I suspect an issue in the database itself, that the source files are not saved correctly in the database. 
In your MongoDB, look for `sources` key in `runs` collection.
It should be something like this -
```
"sources": [
            [
                "augmentations.py",
                ObjectID("5bbd14c2330b926924265d29")
            ]
        ],
```
Then, match this `ObjectID` with `files_id` in `fs.chunks` collection
It should be something like this -
<img width="1154" alt="screen shot 2019-01-19 at 7 55 44 am" src="https://user-images.githubusercontent.com/1051198/51429076-cdfb1b00-1bbf-11e9-8829-1f695ebd7b0f.png">

I want to know if you have `data` key in the `fs.chunks` collection
