### ISSUE TITLE
"Error: No response was received from the server." for larger databases

### ISSUE THREAD

**Issue by wjaskowski** [vivekratnavel/omniboard#47]
For larger databases I get `Error: No response was received from the server.` (I suspect a timeout - sacredboard works fine). Can we remove the timeout?

**Comment by vivekratnavel** [comment]
@wjaskowski There is no timeout set. Can you post a screen-shot of the `network` tab with the response? You can open network tab by `right-click-> Inspect` in chrome.

**Comment by wjaskowski** [comment]
Actually, now I noticed that there is also some error on the console:
```
omniboard -m localhost:27017:magellan_fixed_reproduce
Error: Port 9000 is already in use. Retrying with port 9001...
Error: Port 9001 is already in use. Retrying with port 9002...
Error: Port 9002 is already in use. Retrying with port 9003...
Error: Port 9003 is already in use. Retrying with port 9004...
Omniboard is listening on port 9004!
Connection to mongodb://localhost:27017/magellan_fixed_reproduce established successfully!
::1 - - [17/Jan/2019:09:06:04 +0000] "GET / HTTP/1.1" 304 - 6.053 ms
::1 - - [17/Jan/2019:09:06:04 +0000] "GET /static/css/main.696de9ab.css HTTP/1.1" 304 - 2.882 ms
::1 - - [17/Jan/2019:09:06:04 +0000] "GET /static/js/main.94b5db79.js HTTP/1.1" 304 - 1.007 ms
::1 - - [17/Jan/2019:09:06:04 +0000] "GET /static/css/main.696de9ab.css.map HTTP/1.1" 200 264568 3.357 ms
::1 - - [17/Jan/2019:09:06:05 +0000] "GET /static/media/glyphicons-halflings-regular.448c34a5.woff2 HTTP/1.1" 304 - 0.679 ms
::1 - - [17/Jan/2019:09:06:05 +0000] "GET /api/v1/Runs?distinct=omniboard.tags HTTP/1.1" 304 - 186.179 ms
::1 - - [17/Jan/2019:09:06:05 +0000] "GET /api/v1/Omniboard.Columns HTTP/1.1" 304 - 208.596 ms
::1 - - [17/Jan/2019:09:06:05 +0000] "GET /api/v1/Omniboard.Config.Columns HTTP/1.1" 304 - 208.112 ms
::1 - - [17/Jan/2019:09:06:06 +0000] "GET /static/js/main.94b5db79.js.map HTTP/1.1" 200 25799181 5.647 ms

<--- Last few GCs --->

[17109:0x55a75079ecd0]    56473 ms: Mark-sweep 1451.1 (1550.2) -> 1451.0 (1499.8) MB, 666.9 / 0.0 ms  last resort GC in old space requested
[17109:0x55a75079ecd0]    57139 ms: Mark-sweep 1451.0 (1499.8) -> 1451.0 (1492.2) MB, 665.6 / 0.0 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x7a02c399099 <JSObject>
    1: fromString(aka fromString) [buffer.js:314] [bytecode=0x2292d956bd41 offset=164](this=0x7a02c382241 <undefined>,string=0x2ea02064a659 <Very long string[369992631]>,encoding=0x7a02c3f0551 <String[4]: utf8>)
    2: from [buffer.js:177] [bytecode=0x2292d956b849 offset=11](this=0x2c4e79a48b09 <JSFunction Buffer (sfi = 0x2e8f5732a8f9)>,value=0x2ea02064a659 <Very long string[369992631]>,encodingO...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [node]
 2: 0x55a74daaadd4 [node]
 3: v8::Utils::ReportOOMFailure(char const*, bool) [node]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [node]
 5: v8::internal::Factory::NewRawOneByteString(int, v8::internal::PretenureFlag) [node]
 6: v8::internal::String::SlowFlatten(v8::internal::Handle<v8::internal::ConsString>, v8::internal::PretenureFlag) [node]
 7: v8::String::WriteUtf8(char*, int, int*, int) const [node]
 8: node::StringBytes::Write(v8::Isolate*, char*, unsigned long, v8::Local<v8::Value>, node::encoding, int*) [node]
 9: node::Buffer::New(v8::Isolate*, v8::Local<v8::String>, node::encoding) [node]
10: 0x55a74dac9768 [node]
11: v8::internal::FunctionCallbackArguments::Call(void (*)(v8::FunctionCallbackInfo<v8::Value> const&)) [node]
12: 0x55a74dcdeb63 [node]
13: 0x55a74dcdf0bf [node]
14: 0x3e8afdf040bd
[1]    17109 abort (core dumped)  omniboard -m localhost:27017:magellan_fixed_reproduce
```
![screenshot_2019-01-17_10-07-52](https://user-images.githubusercontent.com/4952605/51307438-fa882900-1a3f-11e9-9749-668a47bd4bef.png)

**Comment by vivekratnavel** [comment]
@wjaskowski I am trying to reproduce this issue in my environment, but with no success. How big is your database. How many rows do you have?

**Comment by wjaskowski** [comment]
75 rows

**Comment by vivekratnavel** [comment]
@wjaskowski I have tried running omniboard with 1100 rows and it runs fine. It might also be because you have different number of configs than mine etc. But, I am also going to try with a couple thousand more rows. 

I am curious on how much memory (RAM) your VM or machine has where omniboard server is running. 
Can you try running omniboard on a different machine with bigger memory and let me know if you hitting the same issue? Because 75 rows is not big at all

**Comment by wjaskowski** [comment]
I agree. I have 32GB of RAM. Since this problem happens only for a single
database it not a big problem currently. Let's see if it happen again.

**Comment by matzek92** [comment]
I'm facing the same problem. My database currently has around 150 entries. Starting omniboard with --max-old-space-size=16384 option for nodejs increases the memory. But omniboard is very slow and produces sometimes produces some other errors. Is it possible that (many) artifacts or large logfiles cause the problem? (I use version 0.11.0 from npm)

**Comment by vivekratnavel** [comment]
@matzek92 What other errors are you getting? Roughly how many artifacts do you have per run? Large log files shouldn't affect performance since they are fetched only after any particular row is selected.

**Comment by matzek92** [comment]
Currently I do store validation results and model parameters as artifacts.
- On Average there are ~100 validation result files. Size (~1MB each)   
- I save 3 models as artifacts (initial, best on validation, final). Size (~50MB-300MB each)

Most of the time the Browser tabs ran out of memory.

**Comment by matzek92** [comment]
Here is another one:

http://127.0.0.1:9000/api/v1/Runs?select=_id,heartbeat,experiment,command,artifacts,host,stop_time,config,result,start_time,resources,format,status,omniboard,metrics,meta&sort=-_id&query=%7B%22$and%22:[%7B%22_id%22:%7B%22$eq%22:49%7D%7D]%7D&populate=metrics net::ERR_CACHE_WRITE_FAILURE 304 (Not Modified)

**Comment by vivekratnavel** [comment]
@matzek92 Does your browser tab crash when you try to browse `artifacts` or does it crash always?

Artifacts are loaded only when you click on any row and select `Artifacts` tab. Are you able to see the list of runs initially?

**Comment by matzek92** [comment]
Most of the time the tab already crashes before due to OUT_OF_MEMORY errors.

**Comment by JarnoRFB** [comment]
I get the same error with 8500 entries.

**Comment by matzek92** [comment]
I do capture many metric values so maybe the "populate=metrics"  might cause some of the performance problems. (see the http request posted above)

**Comment by vivekratnavel** [comment]
I am working on a patch to improve performance. Here is my approach -

- Instead of fetching all artifacts when user clicks on `Artifacts` tab, fetch only metadata of artifacts to display the accordion of artifacts.
- Use infinite scrolling ([React List](https://github.com/coderiety/react-list)) to render accordions instead of native react rendering to better support large number of artifacts
- Fetch only one chunk of the artifact for preview and not load all the chunks
- Use Node Streams API to stream artifacts data instead of hogging up server memory to handle individual file downloads

I am still figuring out the best way to handle `Download All` artifacts or source files without crashing the server.

**Comment by matzek92** [comment]
@vivekratnavel 
I just tested removing the mongoose autopopulation of the metrics. That immediately solved the memory issues for me. Uncommenting line 191 in web/src/components/RunsTable/runsTable.js does the job.
```
[...]
//  populate: 'metrics'
[...]
```
I  think that was the main reason for the memory problems I explored.

The performance optimizations for Artifacts would be great as well.

**Comment by vivekratnavel** [comment]
> I am working on a patch to improve performance. Here is my approach -
> 
> * Instead of fetching all artifacts when user clicks on `Artifacts` tab, fetch only metadata of artifacts to display the accordion of artifacts.
> * Use infinite scrolling ([React List](https://github.com/coderiety/react-list)) to render accordions instead of native react rendering to better support large number of artifacts
> * Fetch only one chunk of the artifact for preview and not load all the chunks
> * Use Node Streams API to stream artifacts data instead of hogging up server memory to handle individual file downloads
> 
> I am still figuring out the best way to handle `Download All` artifacts or source files without crashing the server.

These performance optimizations were committed as part of #71

**Comment by shoeffner** [comment]
Using the docker image from 4 days ago (coinciding with https://github.com/vivekratnavel/omniboard/issues/47#issuecomment-468576383) I get the same error with about 250 rows (maybe even earlier, I didn't check it in the evening but only when I got back in the morning when more than 200 rows were already populated).

To reproduce the error you can try https://github.com/shoeffner/gan_table_setting: `docker-compose up` will bring up a mongoDB and the omniboard (using a docker volume, make sure to clean up later). 
Then, using `python optimize_hyperparameters.py` will queue 1000 experiments. These experiments can then be consumed by runners (`./runner.sh`). I had 8 runners working on the experiment queue over night and checked omniboard in the morning, thus I don't know when it started to happen.

The full error is very similar to the one posted above, here the log of docker-compose (cleaned to only contain omniboard and no mongodb output):

```
omniboard_1  |
omniboard_1  | > omniboard@1.0.0 prod /usr/omniboard
omniboard_1  | > cross-env NODE_ENV=production node dist/index.js "--mu" "mongodb://mongo:27017/sacred"
omniboard_1  |
omniboard_1  | Omniboard is listening on port 9000!
omniboard_1  | Connection to mongodb://mongo:27017/sacred established successfully!
omniboard_1  | ::ffff:172.18.0.1 - - [05/Mar/2019:09:25:05 +0000] "GET / HTTP/1.1" 304 - 9.437 ms
omniboard_1  | ::ffff:172.18.0.1 - - [05/Mar/2019:09:25:06 +0000] "GET /static/css/main.2fdf4e28.css HTTP/1.1" 304 - 1.663 ms
omniboard_1  | ::ffff:172.18.0.1 - - [05/Mar/2019:09:25:06 +0000] "GET /static/js/main.bc650d99.js HTTP/1.1" 304 - 0.783 ms
omniboard_1  | ::ffff:172.18.0.1 - - [05/Mar/2019:09:25:07 +0000] "GET /favicon.ico?v=1 HTTP/1.1" 304 - 0.697 ms
omniboard_1  | ::ffff:172.18.0.1 - - [05/Mar/2019:09:25:13 +0000] "GET /api/v1/database HTTP/1.1" 304 - 6.078 ms
omniboard_1  | ::ffff:172.18.0.1 - - [05/Mar/2019:09:25:13 +0000] "GET /api/v1/Runs?distinct=omniboard.tags HTTP/1.1" 304 - 55.080 ms
omniboard_1  | ::ffff:172.18.0.1 - - [05/Mar/2019:09:25:14 +0000] "GET /api/v1/Omniboard.Config.Columns HTTP/1.1" 304 - 826.351 ms
omniboard_1  | ::ffff:172.18.0.1 - - [05/Mar/2019:09:25:14 +0000] "GET /api/v1/Omniboard.Columns HTTP/1.1" 304 - 846.378 ms
omniboard_1  |
omniboard_1  | <--- Last few GCs --->
omniboard_1  |
omniboard_1  | [23:0x2ba8ac0]    37442 ms: Mark-sweep 1396.0 (1422.5) -> 1393.7 (1418.3) MB, 1018.4 / 0.0 ms  (+ 0.1 ms in 22 steps since start of marking, biggest step 0.0 ms, walltime since start of marking 1054 ms) (average mu = 0.151, current mu = 0.053) allocation [23:0x2ba8ac0]    37465 ms: Scavenge 1397.4 (1421.3) -> 1397.5 (1423.3) MB, 12.8 / 0.0 ms  (average mu = 0.151, current mu = 0.053) allocation failure
omniboard_1  |
omniboard_1  |
omniboard_1  | <--- JS stacktrace --->
omniboard_1  |
omniboard_1  | ==== JS stack trace =========================================
omniboard_1  |
omniboard_1  |     0: ExitFrame [pc: 0x15d3a5e841bd]
omniboard_1  | Security context: 0x65b3ba9e789 <JSObject>
omniboard_1  |     1: readDoubleForwards [0x30e71c8b0261] [internal/buffer.js:~444] [pc=0x15d3a61e1d4c](this=0x183d8e1f8041 <Uint8Array map = 0x18118554ee91>,/* anonymous */=16709727)
omniboard_1  |     2: deserializeObject(aka deserializeObject) [0x2a6b3dfd4539] [/usr/omniboard/node_modules/bson/lib/bson/parser/deserializer.js:~41] [pc=0x15d3a61eb7dd](this=0x2416dff022e1 <undefined>,buff...
omniboard_1  |
omniboard_1  | FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
omniboard_1  |  1: 0x8b8210 node::Abort() [node]
omniboard_1  |  2: 0x8b825c  [node]
omniboard_1  |  3: 0xac1d1e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
omniboard_1  |  4: 0xac1f38 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
omniboard_1  |  5: 0xeb11f2  [node]
omniboard_1  |  6: 0xebd14a v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [node]
omniboard_1  |  7: 0xebdab4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
omniboard_1  |  8: 0xec03e5 v8::internal::Heap::AllocateRawWithRetry(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [node]
omniboard_1  |  9: 0xe888c4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [node]
omniboard_1  | 10: 0x112a2ae v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [node]
omniboard_1  | 11: 0x15d3a5e841bd
omniboard_1  | npm ERR! code ELIFECYCLE
omniboard_1  | npm ERR! errno 1
omniboard_1  | npm ERR! omniboard@1.0.0 prod: `cross-env NODE_ENV=production node dist/index.js "--mu" "mongodb://mongo:27017/sacred"`
omniboard_1  | npm ERR! Exit status 1
omniboard_1  | npm ERR!
omniboard_1  | npm ERR! Failed at the omniboard@1.0.0 prod script.
omniboard_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
omniboard_1  |
omniboard_1  | npm ERR! A complete log of this run can be found in:
omniboard_1  | npm ERR!     /root/.npm/_logs/2019-03-05T09_26_00_901Z-debug.log
```

And here is the referenced *-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/omniboard/node_modules/.bin/npm',
1 verbose cli   'run',
1 verbose cli   'prod',
1 verbose cli   '--',
1 verbose cli   '--mu',
1 verbose cli   'mongodb://mongo:27017/sacred' ]
2 info using npm@6.5.0
3 info using node@v10.8.0
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle omniboard@1.0.0~preprod: omniboard@1.0.0
6 info lifecycle omniboard@1.0.0~prod: omniboard@1.0.0
7 verbose lifecycle omniboard@1.0.0~prod: unsafe-perm in lifecycle true
8 verbose lifecycle omniboard@1.0.0~prod: PATH: /usr/omniboard/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/omniboard/node_modules/.bin:/usr/omniboard/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle omniboard@1.0.0~prod: CWD: /usr/omniboard
10 silly lifecycle omniboard@1.0.0~prod: Args: [ '-c',
10 silly lifecycle   'cross-env NODE_ENV=production node dist/index.js "--mu" "mongodb://mongo:27017/sacred"' ]
11 silly lifecycle omniboard@1.0.0~prod: Returned: code: 1  signal: null
12 info lifecycle omniboard@1.0.0~prod: Failed to exec prod script
13 verbose stack Error: omniboard@1.0.0 prod: `cross-env NODE_ENV=production node dist/index.js "--mu" "mongodb://mongo:27017/sacred"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/omniboard/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:182:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/omniboard/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:182:13)
13 verbose stack     at maybeClose (internal/child_process.js:962:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:249:5)
14 verbose pkgid omniboard@1.0.0
15 verbose cwd /usr/omniboard
16 verbose Linux 4.9.0-8-amd64
17 verbose argv "/usr/local/bin/node" "/usr/omniboard/node_modules/.bin/npm" "run" "prod" "--" "--mu" "mongodb://mongo:27017/sacred"
18 verbose node v10.8.0
19 verbose npm  v6.5.0
20 error code ELIFECYCLE
21 error errno 1
22 error omniboard@1.0.0 prod: `cross-env NODE_ENV=production node dist/index.js "--mu" "mongodb://mongo:27017/sacred"`
22 error Exit status 1
23 error Failed at the omniboard@1.0.0 prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Maybe it helps in tracking down the issue.

@matzek92's idea of commenting `//  populate: 'metrics'` works.

**Comment by vivekratnavel** [comment]
@shoeffner I have added unit tests to @matzek92's patch and is ready to be merged. It should definitely improve the performance.
