### ISSUE TITLE
Cannot inspect experiments on the bottom of the page

### ISSUE THREAD

**Issue by wjaskowski** [vivekratnavel/omniboard#48]
If I have many experiments (so I need to scroll to get to the most bottom ones), I am unable to inspect the ones at the bottom. When I open them, the plots open but they show up outside the screen and the *main* scroll on the right is not updated to let me scroll more.

**Comment by danielcrane** [comment]
I'm also experiencing the same.

**Comment by vivekratnavel** [comment]
This a bug in Fixed data table 2 - https://github.com/schrodinger/fixed-data-table-2/issues/360

They claim to have resolved this issue in v1.0, but since it is still in beta, I am going to wait until stable release for migration to v1.0

**Comment by shakenes** [comment]
I'm still experiencing this issue. Since Fixed data table 2 v1.0 is already released, will there be an update on this?
