### ISSUE TITLE
X-Axis Type should be "steps" by default

### ISSUE THREAD

**Issue by wjaskowski** [vivekratnavel/omniboard#51]
Currently, neither "steps" nor "timestamps" are set by default and this results in X's being consecutive numbers starting from 0, instead of steps.

**Comment by vivekratnavel** [comment]
@wjaskowski X-Axis type is indeed set to `Steps` by default. Which browser do you use to run omniboard? Can you try it in Chrome and also by resetting the [cache](https://vivekratnavel.github.io/omniboard/#/troubleshooting?id=reset-cache) and let me know?

**Comment by wjaskowski** [comment]
Chrome. Sure. In a week. On holidays.

**Comment by vivekratnavel** [comment]
Sure. Enjoy your holidays! :)

**Comment by vivekratnavel** [comment]
Fix released in [v0.10.1](https://github.com/vivekratnavel/omniboard/releases/tag/0.10.1)
