### ISSUE TITLE
A config tab

### ISSUE THREAD

**Issue by wjaskowski** [vivekratnavel/omniboard#52]
The sacredboard had a config tab (all config options listed). Omniboard has columns, which are nice but are of no use if one has 50 config options. A sacredboard-style config tab would be nice to have.

**Comment by vivekratnavel** [comment]
This feature was already released in v0.8.0 - https://github.com/vivekratnavel/omniboard/releases/tag/0.8.0

@wjaskowski Update your omniboard to latest version and let me know if the feature you are requesting is something different

**Comment by vivekratnavel** [comment]
Closing this as there was no response for two weeks.
