### ISSUE TITLE
Build plots from metric and config columns

### ISSUE THREAD

**Issue by dwright37** [vivekratnavel/omniboard#55]
It would be useful to be able to generate plots based on metric and config columns. For example, if I have several runs with different learning rates where I am measuring F1 score, I would like to be able to generate a plot of "F1 vs. Learning Rate" for those runs. So it would involve:

- Ability to select a column to use as the X axis and a column to use as the Y axis
- Ability to filter which runs are present in the plot
- Generate a plot based on this criteria

**Comment by saluto** [comment]
That could be related to/combined with #60. I would love to use these feature!

**Comment by vivekratnavel** [comment]
This feature has been released in version 2.2.0
