### ISSUE TITLE
Password protection

### ISSUE THREAD

**Issue by Gonzalo933** [vivekratnavel/omniboard#56]
I think it's interesting to have an omniboard served running in the cloud so I can access it from any computer, just connecting to the ip, without having to install it.

The problem is that there is not any security feature to prevent unauthorized access. I think an easy feature to implement would be a new launch option from the command line, for example:
` -p password`

With this option omniboard will ask for a password everytime someone tries to access the url.

**Comment by keithcallenberg** [comment]
I agree that this is a fairly common need and _could_ be answered as a feature in omniboard. I do want to say that there are a lot of different scenarios other users may have, and so in the meantime at least, I'd suggest protecting with a reverse proxy, e.g. [oauth2_proxy](https://github.com/pusher/oauth2_proxy).

**Comment by Gonzalo933** [comment]
In the meantime I am using this: https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-http-basic-authentication/

It's easy to add if you are using Nginx
