### ISSUE TITLE
Feature Request: Live Update Table

### ISSUE THREAD

**Issue by kilsenp** [vivekratnavel/omniboard#57]
This does not have a high priority to me, but nevertheless would make the overall experience nicer.

I keep reloading omniboard to see
- new experiments
- new results
- current progress

Therefore, it would be very convenient, if running experiments would update continuously while they are running until they finish.

This is similar to #2 but that it is not just for Captured Out but for the whole table view for running experiments.

Additionally, it would be cool if also new experiments were displayed automatically.

As I said, I don't see this as very urgent, as a refresh isn't the world, but it would still nice to see it at some point.

If I have time, I am also going to look into it myself. But it seems to me that it requires more work. 

I guess a simple solution would be to just automatically reload omniboard every few seconds, but this would then be awful while looking through the different runs. 
It would be nicer if just the values in the columns of running experiments are being refreshed. This would for example allow for a nice display of progress or the current validation score etc.

**Comment by vivekratnavel** [comment]
Auto reload options are added to the top right corner of Omniboard. Enabling auto reload will refresh the table every 30 seconds.
<img width="405" alt="Screen Shot 2019-03-13 at 12 39 00 AM" src="https://user-images.githubusercontent.com/1051198/54261219-724a6f80-4528-11e9-9c14-4a9fec2642eb.png">

**Comment by kilsenp** [comment]
Hi vivetkratnavel,

thank you for working on this!

One major problem with the current implementation is, that it reloads no matter if you are currently checking some experiment.
This makes it kind of annoying and I actually have this function turned off right now.

I am suggesting that instead of reloading full page, it should only refresh each entry.
I had looked into it myself, and currently it's not an easy problem to solve because it needs some major refactoring.
Currently, the code is quite monolithic that is just one massive function that loads all the data.
I have started refactoring but haven't gotten that far, but my idea was that it would just update the data of the existing runs. (not quite sure how to do new runs yet).
This would be much less annoying during usage.
In my opinion, this direction is the way to go, the current implementation has too many drawbacks.

The goal from my changes so far, was to separate the building of the table and getting the data.
Then it will be easier to later get the data for only running runs and update them accordingly.

Unfortunately, it's quite some effort that I haven't gotten that far also due to the fact, that I really have not worked much with React.

But maybe we can get it done more easily by working together. I created a pull request (#76) with my changes so far (this is very much work in progress!). 
I saw that there were quite some changes done to runTable.js which will also need to be implemented there again.

Thanks!

**Comment by vivekratnavel** [comment]
@kilsenp I agree with you that this might be an annoying user experience when the user is looking at any experiment.

Could you please elaborate on what data you want to refresh on each entry?

While on "Captured Out" tab, the logs get automatically refreshed for "running" experiments. Updates to other tabs like "Metrics Plot" and "Artifacts" for running experiments might be useful.

But, in general, I think implementing web sockets and pushing just the updates (delta) to the clients would solve all the problems in this case. Web sockets will take care of pushing new experiments to the clients (browser). But, again it will take a significant amount of refactor and effort to move to web sockets. Before taking that approach, I will do the feasibility study and update here.

Let me know what you think.

**Comment by kilsenp** [comment]
Thanks for coming back to this.

For me it would be most importantly the columns of each 'active' run. That would then be mainly metric columns, later if they are added, run info columns. Basically everything that might change while the experiment is still running.
So not for the view you get, when a run is expanded (that's another story) but just the current table view.

I don't quite understand how websockets would help. What's the server in your example?
As mentioned, I am not too familiar with Javascript and React, but given this example from the React-table documentation 
```
const data = [{
    name: 'Tanner Linsley',
    age: 26,
    friend: {
      name: 'Jason Maurer',
      age: 23,
    }
  },{
    ...
  }]
const columns = [{
    Header: 'Name',
    accessor: 'name' // String-based value accessors!
  }, {
    Header: 'Age',
    accessor: 'age',
    Cell: props => <span className='number'>{props.value}</span> // Custom cell components!
  }, {
    id: 'friendName', // Required because our accessor is not a string
    Header: 'Friend Name',
    accessor: d => d.friend.name // Custom value accessors!
  }, {
    Header: props => <span>Friend Age</span>, // Custom header components!
    accessor: 'friend.age'
  }]

return <ReactTable
    data={data}
    columns={columns}
  />
```

According to the documentation, the table should just update if you change the data array. Wouldn't that be the most straightforward way?

**Comment by vivekratnavel** [comment]
@kilsenp Yes, updating data array is the straightforward way. 

Let's take an example where runId's 5 & 6 are in "running" state.
  
One way to update the data array is to constantly poll the server for run Ids 5 & 6 every "x" seconds until they transition to "completed" state.

Another way is to use web sockets. In this case, when database is updated, server will push data to clients. So, there is no need of polling. 

In either case, the data array will be updated for just the run Ids that are in "running" state. The first approach is relatively less effort to implement. The second approach will need significant changes to both server and web code base.

**Comment by kilsenp** [comment]
Okay, thanks for the clarification.

To me, it seems not necessary to use web sockets. 

- sacred updates anyway only every 10s
- Having immediate updates does not seem to be very important when running experiments. To me updates every 30s would be fine.

Regarding the websockets: Then the server has to query the database every few seconds, doesn't it?

MongoDB provides something like a streaming API:
https://www.mongodb.com/blog/post/an-introduction-to-change-streams

Shouldn't this work with the just updating the array?

**Comment by vivekratnavel** [comment]
@kilsenp Yes, to use the streams API, we can use web sockets. With web sockets, the server won't have to query the database every few seconds. Web socket connection will listen to MongoDB stream and emit data to clients. Read more about web sockets here - https://medium.com/platform-engineer/web-api-design-35df8167460

**Comment by kilsenp** [comment]
Okay, well nevertheless, you were saying this requires a major rewrite.
And that would be on top of providing the live functionality.

I think it might be easier to first implement it with a fixed time interval. This should already be enough for most people.

Then at some later point switch to change change streams api.
If you are saying that this can be done in one anyway, I obviously don't want to stop you. Just trying to make clear, that for most people it wouldn't be really that necessary to get immediate updates.

**Comment by vivekratnavel** [comment]
Got it! I have started to experiment with web sockets. I will update how it goes. If it is too complex, I will switch to long polling.

**Comment by vivekratnavel** [comment]
Web sockets cannot be used here since we don't have native support from mongodb to stream new entries to the database.

I have created #89 to track this enhancement.
