### ISSUE TITLE
Connecting to admin database instead of sacred

### ISSUE THREAD

**Issue by rajatvd** [vivekratnavel/omniboard#59]
When I run this command (from the [Quick Start](https://vivekratnavel.github.io/omniboard/#/quick-start)):

`omniboard --mu mongodb://user:pwd@host/admin?authMechanism=SCRAM-SHA-1 sacred`

Omniboard is connected to the admin database instead of the sacred database.

**Comment by rajatvd** [comment]
Fixed it by running

`omniboard --mu mongodb://user:pwd@host/sacred?authSource=admin`

Instead

**Comment by thibaudmartinez** [comment]
I encountered the same problem when trying to connect to MongoDB Atlas and Azure Cosmos DB.

Simply using the aforementioned syntax :
`omniboard --mu mongodb://<user>:<pwd>@<host>/<database>[?<optional query parameters]`
solved the problem.

Updating the Quick Start in the doc would probably be helpful to people.

**Comment by vivekratnavel** [comment]
@thibaudmartinez Thanks for reporting! Can you create a PR? Quick start lives here - https://github.com/vivekratnavel/omniboard/blob/master/docs/quick-start.md

**Comment by thibaudmartinez** [comment]
@vivekratnavel Here it is #78 !

**Comment by vivekratnavel** [comment]
Thanks @thibaudmartinez !

**Comment by thibaudmartinez** [comment]
@vivekratnavel Thank you for your work on Omniboard! It's great!
