### ISSUE TITLE
Error while using the omniboard

### ISSUE THREAD

**Issue by nehaboob** [vivekratnavel/omniboard#6]
Hi, 
I installed the omniboard using npm. When I open http://localhost:9000/ in the browser I get below error: Error: h.has is not a function.

Attaching the screenshot here. Please advise.

![omniboard](https://user-images.githubusercontent.com/17593261/46272076-058c7b80-c56d-11e8-96c4-e7ed7bf1f7df.png)

**Comment by vivekratnavel** [comment]
Can you try disabling all browser extensions and try in incognito window? 

If the error still persists, please post a screen-shot of the javascript console and network tab. You can do this by right-clicking and selecting "Inspect Element" in Chrome.

**Comment by nehaboob** [comment]
Its working fine in incognito window. Thanks.
