### ISSUE TITLE
Feature Request: Comparing specified runs (similar to shopping cart comparison)

### ISSUE THREAD

**Issue by jykzel** [vivekratnavel/omniboard#60]
Similar to the feature many online shops have, it might be useful to have a button to compare multiple selected runs (using a checkbox) . This could be shown in an overlay.

![image](https://user-images.githubusercontent.com/7493878/52014997-f3850000-24ae-11e9-9772-283bde501e65.png)

Changed values could be highlighted with a specific color.

**Comment by rajatvd** [comment]
Perhaps comparing metric plots can be done like comparing envs in [visdom](https://github.com/facebookresearch/visdom). That's the only neat feature of visdom which prevents me from completely switching to omniboard.

**Comment by saluto** [comment]
That's a great idea! Comparing parameters and metric plots (like in Visdom) across runs is currently the most important thing I'm missing in Omniboard. Does anyone plan to investigate it? I would really appreciate that a lot.

**Comment by pkern90** [comment]
Could look like in the video:
https://youtu.be/xaybRkapeNE?t=74

Basically:
- Combining the plots into one chart
- Showing a diff of the configs
- Showing a diff of the source files (similar to git diff)

**Comment by SchJens** [comment]
I really, really am looking forward to the option of comparing multiple experiments!! For me, this is the most important value to get out of experiment tracking. I have done a lot of research for alternatives to Sacred+Omniboard, and all of them somehow suck. Sacred+Omniboard could be the perfect tool if comparison of runs was possible! Directly plotting e.g. accuracy as a function of the model parameters just gives so much productivity boost!
Do you have any idea about the effort / time scale on which something like this could be realized?

**Comment by grwlf** [comment]
> Perhaps comparing metric plots can be done like comparing envs in [visdom](https://github.com/facebookresearch/visdom). That's one of the few neat features of visdom (other one being dynamic updates) which prevents me from completely switching to omniboard.

IMO metric plots comparision is more importan than original proposal. For now, this is the main feature missing which prevents us from migrating from tensorboard. It is very important to have an option to view metrics from different runs on the same grpah

**Comment by flukeskywalker** [comment]
Completely support the above comments. Comparison of metrics is the biggest feature preventing my colleagues from switching to Omniboard.

**Comment by lliuz** [comment]
Support all the above comments. I think the lack of comparison for parameters and metrics might be the main drawback compared to other tools like comet.ml.

**Comment by vivekratnavel** [comment]
I am currently working on adding support for this feature. I am expecting to release this feature within a week or so.

**Comment by balloch** [comment]
can you point to the documentation of this functionality?
