### ISSUE TITLE
Feature request: Add tag and notes while experiment is running

### ISSUE THREAD

**Issue by EmanueleGhelfi** [vivekratnavel/omniboard#61]
It would be useful to allow the users to add tag and notes while the experiment is running.
At the moment I can add tag and notes but as soon as I refresh the omniboard page the tags and notes disappear.

**Comment by khaledvic** [comment]
check issue #39 , @kilsenp solution works!

**Comment by EmanueleGhelfi** [comment]
So this is actually related to sacred. Should I install the sacred version linked in the issue?

**Comment by khaledvic** [comment]
Either use his fork or redo the changes (```replace_one``` to ```update_one```).

**Comment by EmanueleGhelfi** [comment]
Thank you!
