### ISSUE TITLE
Feature request: Display image artifacts

### ISSUE THREAD

**Issue by EmanueleGhelfi** [vivekratnavel/omniboard#62]
While working with some generative model (like GAN) it would be useful to inspect the images generated by the model. At the moment I'm saving them as artifacts into sacred.
If I save a large number of artifacts omniboard crashes. 
It would be useful to display image artifacts as images in omniboard.

**Comment by vivekratnavel** [comment]
@EmanueleGhelfi Which extension do you use to save your image artifacts? And how big are those image files? Omniboard tries to display images of known formats. Performance issue is being tracked via #47

**Comment by EmanueleGhelfi** [comment]
I'm using sacred for saving my artifacts. I'm saving images as PNG but
omniboard does not show me the images, only the file name in the artifacts
section. I can download them but it's not an optimal procedure.

**Comment by vivekratnavel** [comment]
Are your image files greater than 2MB?

**Comment by EmanueleGhelfi** [comment]
The should be in the order of some KB. Is there a limit for the image size?

**Comment by vivekratnavel** [comment]
@EmanueleGhelfi There is no limit on the size of the images, but the data is stored in chunks in the database. If your image size is in the order of KBs, chunk size shouldn't really matter and I don't understand why you are not able to view the images. Can you check if you have any errors in the browser console or the server logs?

**Comment by EmanueleGhelfi** [comment]
There are no errors in the server output or in the console log.
The problem is that my image is interpreted as .txt instead of .png.
Omniboard is  displaying this:
![image](https://user-images.githubusercontent.com/16719271/52549904-e54fb180-2dd5-11e9-8c11-f376c89d4889.png)


My code is:
```python
# other imports
...
# sacred
from sacred import Experiment
from sacred.observers import MongoObserver
from sacred.stflow import LogFileWriter

ex = Experiment("sequence_new_dataset")

# observers
ex.observers.append(MongoObserver.create())

# config
ex.add_config("default.json")
ex.add_config("experiment.json")

# train 
@ex.automain
@LogFileWriter(ex)
def train(
# params
)
# code....

g_z_value = sess.run(G_z_rgb_concat, feed_dict)
for i, img in enumerate(g_z_value):
     cv2.imwrite(
                        log_dir + f"/img_step_{step}_{i}.png",
                        cv2.cvtColor((img + 1) * 127.5, cv2.COLOR_RGB2BGR),
                        )
    ex.add_artifact(
                        log_dir + f"/img_step_{step}_{i}.png", f"img_step_{step}_{i}"
                        )
# other code...
```

**Comment by EmanueleGhelfi** [comment]
The bug was caused by the missing artifact extension. I fixed this error with:
```
                for i, img in enumerate(g_z_value):
                    cv2.imwrite(
                        log_dir + f"/img_step_{step}_{i}.png",
                        cv2.cvtColor((img + 1) * 127.5, cv2.COLOR_RGB2BGR),
                    )
                    ex.add_artifact(
                        log_dir + f"/img_step_{step}_{i}.png", f"img_step_{step}_{i}.png"
                    )
                    break
```
Basically the only thing to do is add the extension to the name of the artifact.

**Comment by vivekratnavel** [comment]
@EmanueleGhelfi Yes, without an extension, Omniboard cannot identify images and tries to render as text. You figured it right!
