### ISSUE TITLE
Feature request: multiple select

### ISSUE THREAD

**Issue by kirk86** [vivekratnavel/omniboard#66]
Hi and thanks for omniboard.
I was wondering if it isn't much trouble to add the option of multiple select for ether deleting or editing experiments.

The other thing that would be interesting is how can someone add additional plots for an experiment?

**Comment by vivekratnavel** [comment]
Related to #60

**Comment by Guptajakala** [comment]
@vivekratnavel 
+1. I didn't see the feature in 2.2.0
Has this feature already been added?

**Comment by vivekratnavel** [comment]
Closing this since Omniboard now supports multi-select compare and delete.
