### ISSUE TITLE
Is it possible to download artifacts from Omniboard?

### ISSUE THREAD

**Issue by erikyao** [vivekratnavel/omniboard#7]
Hi Vivek, 

Thank you so much for your efforts in this amazing tool. I am just wondering if in the future there will be links for downloading artifacts. 

Best,
Yao

**Comment by vivekratnavel** [comment]
Thanks for your feedback! 

Could you please elaborate on how you would like to download the artifacts?

**Comment by erikyao** [comment]
E.g. If I trained a DNN model, saved the model in a pickle file, and added this pickle file as a Sacred artifact, can I download this pickle file directly from Omniboard? Restoring the file from MongoDB need some extra efforts. Thanks!

**Comment by vivekratnavel** [comment]
You can now View / Download source files or artifacts from Omniboard. Install Omniboard from source to try this feature and let me know how it works.

**Comment by erikyao** [comment]
Wow, thank you, Vivek!
