### ISSUE TITLE
Omniboard crash related to showing Tags column

### ISSUE THREAD

**Issue by keithcallenberg** [vivekratnavel/omniboard#72]
Omniboard is crashing at the Javascript layer whenever the Tags column is shown. If I reload the page with a window size so narrow that the Tags column does not show, the page loads fine:

![image](https://user-images.githubusercontent.com/999275/53664283-17666d80-3c36-11e9-8c45-63d99c865c50.png)

But if I increase the window width, I get a blank page with the following javascript error:

![image](https://user-images.githubusercontent.com/999275/53664445-8348d600-3c36-11e9-9374-0aa6454f7182.png)

```
TypeError: g.map is not a function
    at t.value (cells.js:4)
    at Dn (react-dom.production.min.js:173)
    at Ln (react-dom.production.min.js:172)
    at Nn (react-dom.production.min.js:180)
    at _r (react-dom.production.min.js:232)
    at wr (react-dom.production.min.js:233)
    at Hr (react-dom.production.min.js:249)
    at Br (react-dom.production.min.js:248)
    at zr (react-dom.production.min.js:245)
    at Mr (react-dom.production.min.js:243)
tr @ react-dom.production.min.js:198
```

I suspect that I accidentally added an _empty_ tag to one of my experiments. But I can't tell because this error is caused by showing the Tag column.

**Comment by vivekratnavel** [comment]
Which version of Omniboard is this? And can you try resetting the cache (https://vivekratnavel.github.io/omniboard/#/troubleshooting?id=reset-cache) ?

**Comment by keithcallenberg** [comment]
I just reset my cache and that did not resolve the issue. We are using the "latest" docker tag and just redeployed today so I think it is Omniboard 1.0.

We deleted all recent experiments and the error went away. Now we are trying to reproduce the error. The error comes back when we try to set "tags" as a Sacred config parameter. We had already been doing this successfully with the "notes" column in the same way. 

Is there a recommended way to add tags via Sacred, before Omniboard?

**Comment by vivekratnavel** [comment]
@keithcallenberg Omniboard does not yet support merging config.tags into its custom tags column. You can create a new issue as a feature request to support it. As a workaround, you can rename config.tags to something else for now and the app wouldn't crash.
