### ISSUE TITLE
Running average on graph

### ISSUE THREAD

**Issue by eukaryote31** [vivekratnavel/omniboard#73]
Would be really helpful for long running experiments with quite a bit of noise, so they don't end up looking like this:
![image](https://user-images.githubusercontent.com/10374151/53845858-ec4a8980-3f67-11e9-81b7-45871a3eb9fa.png)

**Comment by vivekratnavel** [comment]
@eukaryote31 
Could you please elaborate on what exactly do you want as a feature?

Do you want to see a graph with `Running Duration` across all the experiments?

**Comment by eukaryote31** [comment]
I want to be able to have an exponential moving average line imposed on top
of my metric graph and make the original faded.

Vivek Ratnavel Subramanian <notifications@github.com> schrieb am Di., 5.
März 2019, 19:46:

**Comment by elbaro** [comment]
See the screenshot:
https://github.com/plotly/dash-live-model-training

This is called smoothing in tensorboard:
https://stackoverflow.com/questions/42281844/what-is-the-mathematics-behind-the-smoothing-parameter-in-tensorboards-scalar

**Comment by avalcarce** [comment]
Having a controllable smoothing factor (0 to 1) to do this would be very helpful as well.

**Comment by fepegar** [comment]
This is great. I'm trying `sacred` + `omniboard` for the first time. I use `omniboard` through `docker-compose` as explained [here](https://sacred.readthedocs.io/en/latest/examples.html#docker-setup). In the `docker-compose.yml` file, the `omniboard` image is `vivekratnavel/omniboard:latest`, but the version I'm using doesn't have this feature. I checked in [Docker hub](https://hub.docker.com/r/vivekratnavel/omniboard) and the tag says `npm 1.7.0` but also "Updated a month ago".

Is there a reason why the feature is not there? Maybe I just didn't find it in the GUI. Can I help to update the Docker image?

I'm very new to all this, I hope my questions make sense.

**Comment by vivekratnavel** [comment]
Hi @fepegar ,

Thanks for bringing this to my notice! There was an issue with dockerhub builds and I have fixed it now. You should be able to pull `vivekratnavel/omniboard:latest` and see the new changes.

Let me know if it still doesn't work.

**Comment by fepegar** [comment]
It does work, thank you!
