### ISSUE TITLE
Display a collection other than 'runs'

### ISSUE THREAD

**Issue by danielzuegner** [vivekratnavel/omniboard#77]
Hi,

Is there a way to display the results in a collection other than `runs` in omniboard? That would be very useful for me as I store the results of different kinds of experiments in different collections.

Thanks!

**Comment by vivekratnavel** [comment]
@jayargo, @danielzuegner You can now specify any collection for "runs" in a config file as mentioned in the documentation here - https://vivekratnavel.github.io/omniboard/#/quick-start?id=start 

Please try and let me know if it works. Thanks!

**Comment by vivekratnavel** [comment]
Hi @saper0,

Do you see any errors in the server log? Also, can you check if there are any errors in the browser console and make sure experiments are present in the "others" collection?

**Comment by saper0** [comment]
Hi @vivekratnavel,

There are no errors in the server log or browser console and experiments are present in "others". With some experimentation, I found that experiments being displayed by omniboard depends on the ending of the name-string of the collection. If the collection ends with a number or "s", omniboard consistently displays the experiments. I tried ~10 collection names ending in different letters than "s" or a number, and then no experiments were displayed (e.g. a collection named "something" is not working, renaming it to "something_s" is working).

**Comment by saper0** [comment]
Hi @vivekratnavel,

using the "ending with s"-knowledge, I am successfully using omniboard to display my different run collections (all ending with s ;) ). Now, I want to use the [metrics API](https://sacred.readthedocs.io/en/stable/collected_information.html) of sacred. 

When I use a custom metrics collections say `others_metrics` and add to my config file `"metricsCollectionName": "others_metrics"`, omniboard successfully connects to the database and the UI loads with the experiments. However, clicking on any experiment leads to a blank window (after the UI opens for a fraction of a second the details and trying to load the metrics) and I have to reload the page to get the UI back - without the experiment-details showing. 

Omniboard or browser console does not report any errors. Also, I have experiments in `others_metrics` and renaming it to `metrics` and restarting omniboard without `"metricsCollectionName": "others_metrics"` in the config works as intended. 

Should this be a separate issue or the issue opened again?

**Comment by vivekratnavel** [comment]
This is interesting. Could this be related to your browser or OS? Can you share which OS and browser you are trying out? Also, did you try other browsers?

**Comment by saper0** [comment]
Omniboard runs on `Ubuntu 20.04.1 LTS (GNU/Linux 5.4.0-42-generic x86_64)` on a remote server. I access it locally through a ssh tunnel. My local operating system is `Mac OS Moneterey 12.2` and the problem happens with `Firefox version (97.0, 64bit)` and `Chrome Version 98.0.4758.102 (Official Build) (arm64)`, I did not test other configurations. 

The problem only occurs when accessing the metrics collection. I can view experiment details if another "section" is opened by default e.g. "output". However, if I then click "metrics", the window will go blank.
