### ISSUE TITLE
How could I change timestamp to show my local time?

### ISSUE THREAD

**Issue by Haetsal-Lee** [vivekratnavel/omniboard#79]
Currently it show start/end _time in UTC. And I wish I could see those times in my local time.
Is there a way to change the way how omniboard shows timestamp in local manner?

**Comment by vivekratnavel** [comment]
@Haetsal-Lee This could be tricky, since Omniboard doesn't know which timezone the server is in. If Omniboard shows time in UTC, it is because your sacred experiments ran in a server that is in UTC timezone. As a workaround, you can try switching your server timezone to suit yours.

**Comment by Haetsal-Lee** [comment]
@vivekratnavel But I have never set my MongoDB server time in UTC.

- None of my four environments, MongoDB client, server, Omniboard client and server have been in UTC. 
- And as far as I know, when we save Timestamps instance to MongoDB, they are converted to UTC.
- And also sacred itself save times in UTC ([sacred code](https://github.com/IDSIA/sacred/blob/59b6dee67bcb92e82e6e8ea63a8d8d8b6105d67d/sacred/run.py#L313))

**Comment by vivekratnavel** [comment]
@Haetsal-Lee Thanks for bringing this up! I just ran an experiment and can confirm that the timestamps are stored in UTC. I did not notice it until now. I was always under the impression that the timestamps are stored in server timezone.

I will work on adding an option to change the timezone.
