### ISSUE TITLE
Feature Request: The best way to store structured data like confusion matrix?

### ISSUE THREAD

**Issue by Haetsal-Lee** [vivekratnavel/omniboard#83]
Currently, I am exporting artifact( conf_map.html made with plotly.js) for every experiment.
With this, I can download and load confusion matrix and hovering on data points (It would be difficult to read confusion matrix if you save them in image file).
But as you know there will be many redundant html with this way. Could we have a feature like, by setting tag (e.g. cm) with data(e.g. [4,0,0,4]), so that Omniboard could show it with proper method?
I can not think other examples but confusion matrix since Tensorboard already supports things like histogram..
Can anyone suggest a proper way to save confusion matrix?

**Comment by alvarovalcarce** [comment]
What "content_type" do you set in the add_artifact function so that Omniboard renders the plotly HTML properly?

**Comment by vivekratnavel** [comment]
@Haetsal-Lee @alvarovalcarce  I have added support for HTML content type previews in the latest version. Please try and let me know if it works for you.

**Comment by alvarovalcarce** [comment]
It works. Thanks again @vivekratnavel .
Just for future reference, the content_type to use in the save_artifact call is "text/html".
An example of saving a Plotly HTML figure to Omniboard could be:

```python
import plotly.express as px

@ex.main
def main(_run):
   df = px.data.tips()
   fig = px.histogram(df, x="total_bill")
   fig.write_html(filename, include_plotlyjs='cdn')
   _run.add_artifact(filename, name='My_figure.html', content_type="text/html")
```

**Comment by vivekratnavel** [comment]
@alvarovalcarce Thanks for the example code!

It should also work without explicitly specifying the content type.
`_run.add_artifact(filename, name='My_figure.html')`

Omniboard will detect content type from file extension and in this case, any file with extension "html" will get properly rendered as HTML.
