### ISSUE TITLE
Error: h.has is not a function when failed Status is deselected

### ISSUE THREAD

**Issue by eugeneware** [vivekratnavel/omniboard#9]
When you unselect the Status "Failed" from the top left menu you get the following error:

```
Error: h.has is not a function
```

![image](https://user-images.githubusercontent.com/38154/46779342-17d39a00-cd63-11e8-90d1-20784dcfc9be.png)

## Steps to reproduce ##
* Unselect the "Failed" status:

![image](https://user-images.githubusercontent.com/38154/46779381-42bdee00-cd63-11e8-9854-e540d0ac337f.png)

## Environment

* Omniboard 0.02 (both `npm` and current docker versions)
* Ubuntu 16.04

## Notes

* I've disabled browser extensions and tested in latest Chrome / Firefox / Safari with identical results (ie. [This isn't the issue](https://github.com/vivekratnavel/omniboard/issues/6))
* The error appears to be thrown on [this line](https://github.com/vivekratnavel/omniboard/blob/4c8f98f33ee3bf4208b3171d1611783089601824/web/src/components/RunsTable/runsTable.js#L)

**Comment by daanbeverdam** [comment]
Ran into the same problem. This seems to happen every time when there is exactly 1 run to be shown.

**Comment by maartjeth** [comment]
Ran into this as well. Seem to get it at all times though - not only when unselecting failed.
